// Generated by scripts/sync-knowledge.mjs. Do not edit.
export const knowledgePayload = {
  "meta": {
    "name": "NRadio 鲲鹏无限知识库",
    "generated_at": "2026-08-03T00:00:00.000Z",
    "verified_at": "2026-08-03",
    "entry_count": 39,
    "notice": "成员上传资料默认允许收录；动态内容按条目中的日期和适用条件理解。"
  },
  "entries": [
    {
      "id": "upload-20260803-9949756e88-01",
      "title": "马野 C2000MAX 刷机包的内容与作者",
      "text": "这套资料由马野整理，原目录名为“C2000MAX - 刷最新OP教程加挂载TF卡空间”。包内包含刷机说明 TXT、Rufus、DiskGenius Pro、1 张 Rufus 操作图、3 段操作视频，以及 `nradio_c2000-max-SD_0305.img`。知识条目基于对这些本地文件和镜像根文件系统的只读分析，不代表 OpenWrt 或 ImmortalWrt 官方发布。\n\n标签：C2000MAX、马野、刷机包、来源\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "马野",
        "刷机包",
        "来源"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-02",
      "title": "C2000MAX 刷 TF 卡的完整顺序",
      "text": "马野说明的顺序是：先在 C2000MAX 官方系统中把 SD 卡启动优先级保存；用 Rufus 等镜像写入工具把 `nradio_c2000-max-SD_0305.img` 整盘写入 TF 卡；在 Windows DiskGenius 中把镜像之后的未分配空间新建并格式化为 ext4；把卡插回 C2000MAX 后上电；等待 5700 模组自动重启一次且 MAX 主机也重启一次；登录 192.168.7.1 后进入“系统→备份/升级”执行重置，并等待重置和再次重启完成。\n\n标签：C2000MAX、刷机、TF卡、Rufus、DiskGenius、步骤\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "刷机",
        "TF卡",
        "Rufus",
        "DiskGenius",
        "步骤"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-03",
      "title": "C2000MAX 必须先保存 SD 启动优先级",
      "text": "教程第一步发生在设备的官方系统：进入启动相关设置，把 SD/TF 卡设为优先启动并保存。视频显示的是 C2000 MAX 原系统的启动项界面。若未保存，设备可能仍从内部存储启动，看起来像刷卡失败；这时应先确认实际启动介质，而不是反复重写 TF 卡。\n\n标签：C2000MAX、SD启动、官方系统、启动项\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "SD启动",
        "官方系统",
        "启动项"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-04",
      "title": "Rufus 写入的是整盘镜像而不是复制文件",
      "text": "Rufus 中要选中正确的 TF 卡设备，再选择以 `mwrt`/本包镜像结尾的 `.img` 文件并开始写入。写盘会覆盖目标卡的 GPT 和分区，不能把 img 当普通文件复制进现有分区。操作前按容量和设备名再次确认目标卡，防止误覆盖电脑磁盘。\n\n标签：C2000MAX、Rufus、img、整盘写入、数据清除\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "Rufus",
        "img",
        "整盘写入",
        "数据清除"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-05",
      "title": "C2000MAX 镜像的 GPT 分区布局",
      "text": "对镜像 GPT 只读解析得到 6 个分区：bl2（LBA 1024–8191，3.5MiB）、u-boot-env（8192–9215，512KiB）、factory（9216–17407，4MiB）、fip（17408–21503，2MiB）、kernel（21504–87039，32MiB）和 rootfs（87040–496639，200MiB）。镜像文件仅写入了 rootfs 的已用前段，因此写入大容量 TF 后会留下可再分区的尾部空间。不要修改 bl2、u-boot-env、factory 或 fip。\n\n标签：C2000MAX、GPT、bl2、u-boot、factory、fip、kernel、rootfs\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "GPT",
        "bl2",
        "u-boot",
        "factory",
        "fip",
        "kernel",
        "rootfs"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-06",
      "title": "C2000MAX rootfs 的格式和构建时间",
      "text": "rootfs 分区开头是 SquashFS 4.0，小端、XZ 压缩、262144 字节块，文件系统创建时间为 2026-03-03 09:17:40（时间来自镜像元数据）。根文件系统约 36.65MB、3512 个 inode；镜像 SHA-256 为 `f20a5011856d163233dd3b3fc4f1c30a59b544841ff09a09ffc7fff5fc208efd`。这些信息可用于确认用户是否拿到同一版镜像。\n\n标签：C2000MAX、SquashFS、SHA256、固件版本\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "SquashFS",
        "SHA256",
        "固件版本"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-07",
      "title": "C2000MAX 固件的真实发行版身份",
      "text": "镜像不是 OpenWrt 官方固件，而是 `xshark by ImmortalWrt 24.10-SNAPSHOT r33422+3-bf62ca2211`，target 为 `mediatek/filogic`，架构 `aarch64_cortex-a53`，内核 Linux 6.6.94。它带 `no-all override` taint，并含第三方/定制组件。回答软件安装与升级问题时必须按 ImmortalWrt 24.10 snapshot 和本镜像 ABI 处理，不能套用 OpenWrt 25.12 的 apk 命令。\n\n标签：C2000MAX、ImmortalWrt、24.10、Linux6.6.94、mediatek、filogic\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "ImmortalWrt",
        "24.10",
        "Linux6.6.94",
        "mediatek",
        "filogic"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-01",
      "title": "C2000MAX 的设备树和启动参数",
      "text": "kernel FIT 内含 `nradio,c2000-max` 设备树，型号字符串为 `NRadio C2000-MAX`，启动参数使用 `root=PARTLABEL=rootfs rootwait`，说明系统按 GPT 分区标签查找 rootfs 并等待块设备出现。kernel 分区是 ARM64 FIT，包含 Linux 6.6.94 和专用设备树；随意改 rootfs 分区标签可能导致无法启动。\n\n标签：C2000MAX、设备树、FIT、PARTLABEL、rootfs\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "设备树",
        "FIT",
        "PARTLABEL",
        "rootfs"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-02",
      "title": "C2000MAX 默认管理地址和密码",
      "text": "马野教程明确给出管理 IP 为 `192.168.7.1`、Wi‑Fi 密码为 `admin`。只读检查 `/etc/shadow` 还确认 root 密码哈希与明文 `admin` 完全匹配，因此 LuCI/SSH 默认 root 密码也是 admin。首次登录后必须立即更换管理密码和 Wi‑Fi 密码，避免在不可信网络暴露。\n\n标签：C2000MAX、192.168.7.1、admin、默认密码、安全\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "192.168.7.1",
        "admin",
        "默认密码",
        "安全"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-03",
      "title": "C2000MAX 首次启动会有额外自动重启",
      "text": "镜像 `/etc/rc.local` 会检查 `/etc/modules.d/66-mt7993`；若不存在，等待 30 秒、写入 `mt7993` 模块项并重启。这与教程提示的 5700 模组重启一次、MAX 主机重启一次相吻合。首次上电过程中不要过早断电，至少等设备完成自动重启、网络和无线稳定后再操作。\n\n标签：C2000MAX、mt7993、自动重启、5700、首次启动\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "mt7993",
        "自动重启",
        "5700",
        "首次启动"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-04",
      "title": "C2000MAX 首次启动后为何要求执行重置",
      "text": "教程要求首次成功进入系统后，在“系统→备份/升级”执行重置并等待重启。该步骤会重新初始化 overlay/UCI 默认配置，使本机硬件探测、无线配置和首次启动脚本以干净状态落盘。执行重置会清除用户刚做的设置，因此不要在此步骤前投入正式配置；如果设备已有要保留的数据，应先备份。\n\n标签：C2000MAX、重置、overlay、首次启动\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "重置",
        "overlay",
        "首次启动"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-05",
      "title": "C2000MAX 升级不能只在 LuCI 上传固件",
      "text": "马野特别注明，升级该 OP 固件必须重复原步骤 2、3、4：重新把完整 img 写入 TF、重新处理 TF 尾部空间并按完整首次启动过程等待自动重启。虽然镜像的 platform 脚本含 `nradio,c2000-max` 的 eMMC sysupgrade 路径，但本教程分发的是整盘 SD 镜像，不能据此假定任意 LuCI sysupgrade 都安全。升级前备份配置并以作者的新版本说明为准。\n\n标签：C2000MAX、升级、LuCI、sysupgrade、重刷TF\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "升级",
        "LuCI",
        "sysupgrade",
        "重刷TF"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-06",
      "title": "TF 尾部 ext4 分区只是额外存储，不自动扩展 overlay",
      "text": "教程让用户用 DiskGenius 把 TF 卡剩余空间格式化为 ext4。镜像预装 `block-mount`，fstab 全局开启 `anon_mount=1` 和 `auto_mount=1`，因此新分区会被自动挂载成额外存储；但现有 fstab 没有把它指定为 `/overlay`，所以它不会自动增加安装软件包的空间。若目标是系统扩容，需要另做 extroot 配置；若只用于文件、日志或下载，普通挂载即可。\n\n标签：C2000MAX、TF扩容、ext4、anon_mount、extroot、overlay\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "TF扩容",
        "ext4",
        "anon_mount",
        "extroot",
        "overlay"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-07",
      "title": "C2000MAX 存储支持与注意事项",
      "text": "镜像预装 block-mount、fdisk、parted、e2fsprogs、dosfstools、F2FS、exFAT、NTFS3、btrfs 与 USB/UAS 存储驱动，适合识别多种外置介质。TF 卡长期承载日志、代理数据库或 extroot 会产生持续写入，应选高耐久卡并保留配置备份。磁盘操作优先按 UUID 配置，避免设备名变化。\n\n标签：C2000MAX、存储、block-mount、ext4、F2FS、NTFS、btrfs\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "存储",
        "block-mount",
        "ext4",
        "F2FS",
        "NTFS",
        "btrfs"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-01",
      "title": "C2000MAX 默认网络把 eth1 和 hnat 放在 LAN",
      "text": "设备专用 /etc/board.d/02_network 对 nradio,c2000-max 执行 ucidef_set_interface_lan \"eth1 hnat\"，没有在该分支创建标准 WAN。说明这份镜像的默认端口/硬件 NAT 拓扑与普通多口路由器不同，可能由蜂窝模组或后续脚本创建上联。排障时先看 ubus call network.interface dump 和实际拨号接口，不要假设 eth0/wan 就是互联网出口。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "eth1",
        "hnat",
        "LAN",
        "网络",
        "拨号"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-02",
      "title": "C2000MAX 防火墙和加速默认值",
      "text": "固件基于 firewall4：lan zone 的 input/output/forward 均 ACCEPT，wan zone input/forward REJECT、output ACCEPT，并启用 IPv4 masquerade 与 mtu_fix。配置中 fullcone=1，软件和硬件 flow offloading 默认均为 0；同时预装 MediaTek HNAT、WED、TurboACC、MTK HQoS/eQoS。加速、代理、统计和 SQM/限速可能互相影响，性能排障时应一次只启用一种路径并记录 nft/route 状态。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "firewall4",
        "fullcone",
        "HNAT",
        "WED",
        "TurboACC"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-03",
      "title": "C2000MAX 无线驱动与默认生成逻辑",
      "text": "镜像同时含 kmod-mt7993、kmod-mt_wifi7 和厂商 mtwifi 配置层。mtwifi 默认生成脚本会为 2.4G/5G/6G 设置 ImmortalWrt SSID、US 国家码、100% txpower，5G/6G 使用 EHT160，初始生成逻辑的 encryption 为 none；但马野教程称实机 Wi-Fi 密码为 admin，说明首次启动或设备环境还有覆盖。以实机 /etc/config/wireless 为准，并把 country 改为实际使用国家/地区。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "mt7993",
        "WiFi7",
        "EHT160",
        "无线",
        "配置"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-04",
      "title": "C2000MAX 预装的蜂窝与代理组件",
      "text": "镜像预装 qmodem-next、ubus-at-daemon、at-webserver、quectel-CM-5G-M、QMI/MBIM/NCM/RNDIS/串口驱动、MHI/PCIe 驱动、短信转发；也预装 sing-box 与 HomeProxy。它适合蜂窝模组管理和代理分流，但 qmodem、quectel-CM、ModemManager 类工具不应同时抢占同一模组；HomeProxy/sing-box、PBR、mwan 与硬件加速并用时要检查 mark 和路由表。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "5G",
        "qmodem",
        "QMI",
        "MBIM",
        "MHI",
        "HomeProxy",
        "sing-box"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-05",
      "title": "C2000MAX 默认启用的管理服务风险",
      "text": "镜像默认启用 Dropbear、uhttpd、ttyd、SFTP、at-webserver、ubus-at-daemon 等服务。Dropbear 绑定 lan，允许密码和 root 密码登录；uhttpd 同时监听 80/443，但 redirect_https=0；root 默认密码是 admin。虽然标准防火墙不允许 WAN input，若用户把蜂窝/上联误并入 lan 或修改 zone，管理服务可能暴露。建议改强密码、关闭不用的 ttyd/AT Web/SFTP，并启用 HTTPS 管理。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "Dropbear",
        "ttyd",
        "uhttpd",
        "默认服务",
        "安全"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-06",
      "title": "C2000MAX 软件源与内核模块版本风险",
      "text": "固件的 distfeeds 原始地址指向 ImmortalWrt 24.10-SNAPSHOT，首次启动的中文默认脚本会把域名替换为 https://mirrors.vsean.net/openwrt。snapshot 仓库会滚动，而本镜像内核固定为 6.6.94；较新的仓库已经出现不同内核 ABI，因此后续安装 kmod 很可能报 kernel dependency mismatch。不要强装，应使用与镜像同批的软件源/包缓存，或重刷作者提供的完整新镜像。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "opkg",
        "软件源",
        "snapshot",
        "kmod",
        "ABI"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-07",
      "title": "C2000MAX 镜像内可验证的文件哈希",
      "text": "本地包关键 SHA-256：镜像 f20a5011856d163233dd3b3fc4f1c30a59b544841ff09a09ffc7fff5fc208efd；刷机说明 dd2f987bca38faaed87d55bf6b5edc822f3c653f25978f5dd3362970774d5251；Rufus.exe abbf04d50a44a9612c027fc8072f6da67f5bcda2b826f1f852c9c24d7a1fcdff；DiskGenius EXE 736cda5b2775ef1e9b3c1aca74c6bb2adfe737d001dcd935bcbe8ee62958ebbb。哈希只能确认文件一致，不能替代对第三方可执行文件的信任与安全扫描。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "SHA256",
        "Rufus",
        "DiskGenius",
        "完整性"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-01",
      "title": "鲲鹏无限公司与品牌",
      "text": "鲲鹏无限的公司主体为深圳鲲鹏无限科技有限公司，品牌英文名为 NRadio。官方帮助中心称公司创立于 2016 年，是国家高新技术企业和深圳专精特新企业，定位为 5G 无线宽带产品专业厂商。\n\n原条目 ID：company-001\n来源：https://help.nradiowifi.com/\n来源类型：official_help\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：公司、品牌、NRadio、鲲鹏无限",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "公司",
        "品牌",
        "NRadio",
        "鲲鹏无限"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-02",
      "title": "鲲鹏无限团队与创始人介绍",
      "text": "官方帮助中心称，鲲鹏无限核心团队成员来自 TP-LINK、华为、中兴、极路由等通信品牌厂商；创始人张利鹏毕业于清华大学计算机系，并在通信行业深耕十年以上。\n\n原条目 ID：company-002\n来源：https://help.nradiowifi.com/\n来源类型：official_help\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：创始人、张利鹏、团队、公司介绍",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "创始人",
        "张利鹏",
        "团队",
        "公司介绍"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-03",
      "title": "鲲鹏无限主要业务",
      "text": "鲲鹏无限主要提供 4G 和 5G 无线宽带产品，覆盖便携旅行和固定上网两类形态，强调无需铺设传统有线宽带、部署灵活和随用随开。\n\n原条目 ID：company-003\n来源：https://help.nradiowifi.com/\n来源类型：official_help\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：业务、无线宽带、5G CPE、免拉线",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "业务",
        "无线宽带",
        "5G CPE",
        "免拉线"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-04",
      "title": "鲲鹏无限官网产品分类",
      "text": "官网产品中心在 2026 年 7 月 30 日可见的产品类别包括 5G CPE、5G RedCap、全球漫游和高密度 WiFi。选型时应结合完整型号、使用地区、运营商、移动或固定场景、终端数量、网口及供电需求。\n\n原条目 ID：product-001\n来源：https://www.nradiowifi.com/chanpin/\n来源类型：official_web\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：产品中心、产品分类、选型",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "产品中心",
        "产品分类",
        "选型"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-05",
      "title": "C8 系列代表型号",
      "text": "官网在 2026 年 7 月 30 日可见的 C8 系列代表型号包括 C8-788、C8-618、C8-668GL 和 C8-688。相近名称可能对应不同芯片、地区版本、卡槽、频段或接口，回答参数时必须使用完整型号后缀。\n\n原条目 ID：product-002\n来源：https://www.nradiowifi.com/chanpin/fengwozuwang/\n来源类型：official_web\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：5G CPE、C8-788、C8-618、C8-668GL、C8-688",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "5G CPE",
        "C8-788",
        "C8-618",
        "C8-668GL",
        "C8-688"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-06",
      "title": "C2000 与 C5800 系列代表型号",
      "text": "官网在 2026 年 7 月 30 日可见 C2000 MAX、C2000-518、C2000-500、C5800-668GL、C5800-688 和 C5800-650。C2000 系列包含 Mini 5G CPE，C5800 系列包含企业级四卡槽 5G CPE；不同后缀的芯片和配置不可混用。\n\n原条目 ID：product-003\n来源：https://www.nradiowifi.com/chanpin/fengwozuwang/\n来源类型：official_web\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：5G CPE、C2000 MAX、C2000、C5800、企业网络",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "5G CPE",
        "C2000 MAX",
        "C2000",
        "C5800",
        "企业网络"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-01",
      "title": "NBCPE、NBPCE 与户外版代表型号",
      "text": "官网在 2026 年 7 月 30 日可见 NBCPE-668GL、NBPCE-688、NBPCE-650 等 NB68 与 AK68 组合形态，以及 AK68-788 户外版。不同组合和后缀对应的地区、芯片或配置不同，不能视为同一型号。原条目 ID：product-004；来源：https://www.nradiowifi.com/chanpin/fengwozuwang/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high；标签：NBCPE、NBPCE、NB68、AK68、户外CPE。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "NBCPE",
        "NBPCE",
        "NB68",
        "AK68",
        "户外CPE",
        "型号区别",
        "官网产品"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-02",
      "title": "RedCap、Nano CPE 与随身 WiFi 型号",
      "text": "官网在 2026 年 7 月 30 日可见 A8-510 RedCap 5G 移动路由器 CPE、DD-510 Nano 5G CPE、CC-500 与 CC-500 Pro 随身 WiFi，以及 TT-500、TK-500 随身快充 WiFi。原条目 ID：product-005；来源：https://www.nradiowifi.com/chanpin/qiyezuwang/1/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high；标签：RedCap、A8-510、DD-510、随身WiFi、便携。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "RedCap",
        "A8-510",
        "DD-510",
        "随身WiFi",
        "便携",
        "CC-500",
        "TT-500",
        "TK-500",
        "官网产品"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-03",
      "title": "全球漫游与高密度 WiFi 产品",
      "text": "官网在 2026 年 7 月 30 日可见 CC-100GL、TT-100GL、TK-100GL 等全球漫游便携产品，以及 E2000-R 高密度无线接入点和 N6700 AX6000 Wi-Fi 6 四频缓存路由器。全球漫游的实际国家、频段、运营商、套餐和资费应按具体型号及当前服务说明确认。原条目 ID：product-006；来源：https://www.nradiowifi.com/chanpin/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high；标签：全球漫游、高密度WiFi、CC-100GL、E2000-R、N6700。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "全球漫游",
        "高密度WiFi",
        "CC-100GL",
        "E2000-R",
        "N6700",
        "AX6000",
        "Wi-Fi 6",
        "官网产品"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-04",
      "title": "张导严选小店抖音账号",
      "text": "用户提供的短链接解析为“张导严选小店”，抖音号为 70326957594，页面标注为店铺账号，IP 属地广东。该账号可作为选品与交易入口；价格、库存、优惠、发货和售后以当前商品页及订单页面显示为准。原条目 ID：account-001；来源：https://v.douyin.com/IPb2vXHhDqs/；来源类型：douyin_profile；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium_high；标签：抖音、张导严选小店、店铺、购买渠道。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "抖音",
        "张导严选小店",
        "店铺",
        "购买渠道",
        "抖音号70326957594",
        "IP属地广东"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-05",
      "title": "鲲鹏张导抖音账号",
      "text": "用户提供的短链接解析为“鲲鹏张导”，抖音号为 kpzd，IP 属地广东。核对时的公开简介为“鲲鹏CEO张导：清华本硕｜新疆放羊娃”，账号内容围绕 5G 免拉线网络、产品和使用场景展开。原条目 ID：account-002；来源：https://v.douyin.com/SkNGZ72_cAs/；来源类型：douyin_profile；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium_high；标签：抖音、鲲鹏张导、张导、kpzd。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "抖音",
        "鲲鹏张导",
        "张导",
        "kpzd",
        "CEO",
        "5G免拉线"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-06",
      "title": "鲲鹏张导公开视频内容主题",
      "text": "公开可检索作品涉及 NBCPE、C2000 MAX、DD 等产品在车辆、房车、偏远作业区、展会直播、人群密集场所和租房场景中的应用，也包括信号寻找、设备对比、产品拆解、刷机和用户共创。具体视频中的测速、信号或场景效果对应当时的设备、位置和网络条件。原条目 ID：content-001；来源：https://jingxuan.douyin.com/m/video/7632271688436043059；来源类型：douyin_video；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium；标签：使用场景、NBCPE、C2000 MAX、DD、公开视频。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium",
      "tags": [
        "使用场景",
        "NBCPE",
        "C2000 MAX",
        "DD",
        "公开视频",
        "抖音",
        "车辆",
        "房车",
        "偏远作业区",
        "展会直播",
        "人群密集",
        "租房"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-01",
      "title": "C8-660 开放刷机信息",
      "text": "鲲鹏张导的公开视频曾介绍 C8-660 的开放刷机和社区共创策略，并邀请开源社区参与适配。这项信息针对 C8-660 及视频发布时的策略；其他型号是否支持刷机，应根据对应硬件版本和当前固件资料确认。原条目 ID：policy-001；来源：https://jingxuan.douyin.com/m/video/7298330506465119551；来源类型：douyin_video；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium",
      "tags": [
        "C8-660",
        "开放刷机",
        "开源",
        "社区共创"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-02",
      "title": "什么是 5G CPE",
      "text": "5G CPE 接收运营商的 5G 或 4G 蜂窝网络，再通过 WiFi 或网口为手机、电脑、摄像头等终端提供网络。它适合不方便安装有线宽带、需要临时网络、经常移动或希望快速部署网络的场景。原条目 ID：faq-001；来源：https://help.nradiowifi.com/；来源类型：official_help；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "FAQ",
        "5G CPE",
        "原理",
        "无线宽带"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-03",
      "title": "5G CPE 选型前需要确认的信息",
      "text": "推荐 5G CPE 前，应确认使用国家、城市和具体区域，运营商与 SIM 卡套餐，固定或移动使用，室内或户外，同时接入设备数，以及是否需要 2.5G 网口、双卡或多卡、全球漫游、电池、快充、外置天线、户外安装或开放刷机，并了解预算范围。原条目 ID：faq-002；来源：https://www.nradiowifi.com/chanpin/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "FAQ",
        "选型",
        "需求收集",
        "导购"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-04",
      "title": "鲲鹏产品可能适用的场景",
      "text": "官网与鲲鹏张导的公开视频涉及家庭或出租屋免拉线宽带、车辆和房车网络、展会或户外直播、偏远作业区、旅行随身网络和企业多终端接入。实际选型需要结合所在地信号、运营商、终端数、移动性、接口、天线和供电条件。原条目 ID：faq-003；来源：https://www.nradiowifi.com/chanpin/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium_high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "FAQ",
        "使用场景",
        "家庭网络",
        "房车",
        "直播",
        "企业网络"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-05",
      "title": "同一地点不同设备速度不同的原因",
      "text": "同一地点的不同设备可能因蜂窝频段和载波聚合能力、芯片与天线设计、SIM 卡套餐或限速策略、连接基站、设备摆放遮挡以及测试时网络拥塞程度不同而出现速度差异。公平比较应尽量使用同一 SIM 卡、同一位置、相近时间和同一测速服务器。原条目 ID：faq-004；来源：https://help.nradiowifi.com/；来源类型：official_help；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium_high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "FAQ",
        "测速",
        "信号",
        "速度差异",
        "排障"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-06",
      "title": "免拉线宽带与有线宽带的区别",
      "text": "免拉线宽带的主要优势是部署灵活，实际速度和稳定性会随信号、基站容量、蜂窝频段、套餐和环境变化。有线宽带通常更稳定；选择哪种方案应结合安装条件、移动需求、成本和当地网络质量。原条目 ID：faq-005；来源：https://help.nradiowifi.com/；来源类型：official_help；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "FAQ",
        "免拉线",
        "有线宽带",
        "稳定性"
      ]
    }
  ]
}
