// Generated by scripts/sync-knowledge.mjs. Do not edit.
export const knowledgePayload = {
  "meta": {
    "name": "NRadio 鲲鹏无限知识库",
    "generated_at": "2026-08-03T00:00:00.000Z",
    "verified_at": "2026-08-03",
    "entry_count": 92,
    "notice": "成员上传资料默认允许收录；动态内容按条目中的日期和适用条件理解。"
  },
  "entries": [
    {
      "id": "upload-20260803-9949756e88-01",
      "title": "马野 C2000MAX 刷机包的内容与作者",
      "text": "这套资料由马野整理，原目录名为“C2000MAX - 刷最新OP教程加挂载TF卡空间”。包内包含刷机说明 TXT、Rufus、DiskGenius Pro、1 张 Rufus 操作图、3 段操作视频，以及 `nradio_c2000-max-SD_0305.img`。知识条目基于对这些本地文件和镜像根文件系统的只读分析，不代表 OpenWrt 或 ImmortalWrt 官方发布。\n\n标签：C2000MAX、马野、刷机包、来源\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "马野",
        "刷机包",
        "来源"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-02",
      "title": "C2000MAX 刷 TF 卡的完整顺序",
      "text": "马野说明的顺序是：先在 C2000MAX 官方系统中把 SD 卡启动优先级保存；用 Rufus 等镜像写入工具把 `nradio_c2000-max-SD_0305.img` 整盘写入 TF 卡；在 Windows DiskGenius 中把镜像之后的未分配空间新建并格式化为 ext4；把卡插回 C2000MAX 后上电；等待 5700 模组自动重启一次且 MAX 主机也重启一次；登录 192.168.7.1 后进入“系统→备份/升级”执行重置，并等待重置和再次重启完成。\n\n标签：C2000MAX、刷机、TF卡、Rufus、DiskGenius、步骤\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "刷机",
        "TF卡",
        "Rufus",
        "DiskGenius",
        "步骤"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-03",
      "title": "C2000MAX 必须先保存 SD 启动优先级",
      "text": "教程第一步发生在设备的官方系统：进入启动相关设置，把 SD/TF 卡设为优先启动并保存。视频显示的是 C2000 MAX 原系统的启动项界面。若未保存，设备可能仍从内部存储启动，看起来像刷卡失败；这时应先确认实际启动介质，而不是反复重写 TF 卡。\n\n标签：C2000MAX、SD启动、官方系统、启动项\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "SD启动",
        "官方系统",
        "启动项"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-04",
      "title": "Rufus 写入的是整盘镜像而不是复制文件",
      "text": "Rufus 中要选中正确的 TF 卡设备，再选择以 `mwrt`/本包镜像结尾的 `.img` 文件并开始写入。写盘会覆盖目标卡的 GPT 和分区，不能把 img 当普通文件复制进现有分区。操作前按容量和设备名再次确认目标卡，防止误覆盖电脑磁盘。\n\n标签：C2000MAX、Rufus、img、整盘写入、数据清除\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "Rufus",
        "img",
        "整盘写入",
        "数据清除"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-05",
      "title": "C2000MAX 镜像的 GPT 分区布局",
      "text": "对镜像 GPT 只读解析得到 6 个分区：bl2（LBA 1024–8191，3.5MiB）、u-boot-env（8192–9215，512KiB）、factory（9216–17407，4MiB）、fip（17408–21503，2MiB）、kernel（21504–87039，32MiB）和 rootfs（87040–496639，200MiB）。镜像文件仅写入了 rootfs 的已用前段，因此写入大容量 TF 后会留下可再分区的尾部空间。不要修改 bl2、u-boot-env、factory 或 fip。\n\n标签：C2000MAX、GPT、bl2、u-boot、factory、fip、kernel、rootfs\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "GPT",
        "bl2",
        "u-boot",
        "factory",
        "fip",
        "kernel",
        "rootfs"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-06",
      "title": "C2000MAX rootfs 的格式和构建时间",
      "text": "rootfs 分区开头是 SquashFS 4.0，小端、XZ 压缩、262144 字节块，文件系统创建时间为 2026-03-03 09:17:40（时间来自镜像元数据）。根文件系统约 36.65MB、3512 个 inode；镜像 SHA-256 为 `f20a5011856d163233dd3b3fc4f1c30a59b544841ff09a09ffc7fff5fc208efd`。这些信息可用于确认用户是否拿到同一版镜像。\n\n标签：C2000MAX、SquashFS、SHA256、固件版本\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "SquashFS",
        "SHA256",
        "固件版本"
      ]
    },
    {
      "id": "upload-20260803-9949756e88-07",
      "title": "C2000MAX 固件的真实发行版身份",
      "text": "镜像不是 OpenWrt 官方固件，而是 `xshark by ImmortalWrt 24.10-SNAPSHOT r33422+3-bf62ca2211`，target 为 `mediatek/filogic`，架构 `aarch64_cortex-a53`，内核 Linux 6.6.94。它带 `no-all override` taint，并含第三方/定制组件。回答软件安装与升级问题时必须按 ImmortalWrt 24.10 snapshot 和本镜像 ABI 处理，不能套用 OpenWrt 25.12 的 apk 命令。\n\n标签：C2000MAX、ImmortalWrt、24.10、Linux6.6.94、mediatek、filogic\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/278219b3-bb14-43db-a73c-a1c6c82dfd1c-c2000max-maye-part-01-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "ImmortalWrt",
        "24.10",
        "Linux6.6.94",
        "mediatek",
        "filogic"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-01",
      "title": "C2000MAX 的设备树和启动参数",
      "text": "kernel FIT 内含 `nradio,c2000-max` 设备树，型号字符串为 `NRadio C2000-MAX`，启动参数使用 `root=PARTLABEL=rootfs rootwait`，说明系统按 GPT 分区标签查找 rootfs 并等待块设备出现。kernel 分区是 ARM64 FIT，包含 Linux 6.6.94 和专用设备树；随意改 rootfs 分区标签可能导致无法启动。\n\n标签：C2000MAX、设备树、FIT、PARTLABEL、rootfs\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "设备树",
        "FIT",
        "PARTLABEL",
        "rootfs"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-02",
      "title": "C2000MAX 默认管理地址和密码",
      "text": "马野教程明确给出管理 IP 为 `192.168.7.1`、Wi‑Fi 密码为 `admin`。只读检查 `/etc/shadow` 还确认 root 密码哈希与明文 `admin` 完全匹配，因此 LuCI/SSH 默认 root 密码也是 admin。首次登录后必须立即更换管理密码和 Wi‑Fi 密码，避免在不可信网络暴露。\n\n标签：C2000MAX、192.168.7.1、admin、默认密码、安全\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "192.168.7.1",
        "admin",
        "默认密码",
        "安全"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-03",
      "title": "C2000MAX 首次启动会有额外自动重启",
      "text": "镜像 `/etc/rc.local` 会检查 `/etc/modules.d/66-mt7993`；若不存在，等待 30 秒、写入 `mt7993` 模块项并重启。这与教程提示的 5700 模组重启一次、MAX 主机重启一次相吻合。首次上电过程中不要过早断电，至少等设备完成自动重启、网络和无线稳定后再操作。\n\n标签：C2000MAX、mt7993、自动重启、5700、首次启动\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "mt7993",
        "自动重启",
        "5700",
        "首次启动"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-04",
      "title": "C2000MAX 首次启动后为何要求执行重置",
      "text": "教程要求首次成功进入系统后，在“系统→备份/升级”执行重置并等待重启。该步骤会重新初始化 overlay/UCI 默认配置，使本机硬件探测、无线配置和首次启动脚本以干净状态落盘。执行重置会清除用户刚做的设置，因此不要在此步骤前投入正式配置；如果设备已有要保留的数据，应先备份。\n\n标签：C2000MAX、重置、overlay、首次启动\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "重置",
        "overlay",
        "首次启动"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-05",
      "title": "C2000MAX 升级不能只在 LuCI 上传固件",
      "text": "马野特别注明，升级该 OP 固件必须重复原步骤 2、3、4：重新把完整 img 写入 TF、重新处理 TF 尾部空间并按完整首次启动过程等待自动重启。虽然镜像的 platform 脚本含 `nradio,c2000-max` 的 eMMC sysupgrade 路径，但本教程分发的是整盘 SD 镜像，不能据此假定任意 LuCI sysupgrade 都安全。升级前备份配置并以作者的新版本说明为准。\n\n标签：C2000MAX、升级、LuCI、sysupgrade、重刷TF\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "升级",
        "LuCI",
        "sysupgrade",
        "重刷TF"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-06",
      "title": "TF 尾部 ext4 分区只是额外存储，不自动扩展 overlay",
      "text": "教程让用户用 DiskGenius 把 TF 卡剩余空间格式化为 ext4。镜像预装 `block-mount`，fstab 全局开启 `anon_mount=1` 和 `auto_mount=1`，因此新分区会被自动挂载成额外存储；但现有 fstab 没有把它指定为 `/overlay`，所以它不会自动增加安装软件包的空间。若目标是系统扩容，需要另做 extroot 配置；若只用于文件、日志或下载，普通挂载即可。\n\n标签：C2000MAX、TF扩容、ext4、anon_mount、extroot、overlay\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "TF扩容",
        "ext4",
        "anon_mount",
        "extroot",
        "overlay"
      ]
    },
    {
      "id": "upload-20260803-f7dbd2ee59-07",
      "title": "C2000MAX 存储支持与注意事项",
      "text": "镜像预装 block-mount、fdisk、parted、e2fsprogs、dosfstools、F2FS、exFAT、NTFS3、btrfs 与 USB/UAS 存储驱动，适合识别多种外置介质。TF 卡长期承载日志、代理数据库或 extroot 会产生持续写入，应选高耐久卡并保留配置备份。磁盘操作优先按 UUID 配置，避免设备名变化。\n\n标签：C2000MAX、存储、block-mount、ext4、F2FS、NTFS、btrfs\n来源：local-source://C2000MAX-MaYe-package",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/26050dfe-e00b-4055-820a-5266b9a9d9c9-c2000max-maye-part-02-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "存储",
        "block-mount",
        "ext4",
        "F2FS",
        "NTFS",
        "btrfs"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-01",
      "title": "C2000MAX 默认网络把 eth1 和 hnat 放在 LAN",
      "text": "设备专用 /etc/board.d/02_network 对 nradio,c2000-max 执行 ucidef_set_interface_lan \"eth1 hnat\"，没有在该分支创建标准 WAN。说明这份镜像的默认端口/硬件 NAT 拓扑与普通多口路由器不同，可能由蜂窝模组或后续脚本创建上联。排障时先看 ubus call network.interface dump 和实际拨号接口，不要假设 eth0/wan 就是互联网出口。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "eth1",
        "hnat",
        "LAN",
        "网络",
        "拨号"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-02",
      "title": "C2000MAX 防火墙和加速默认值",
      "text": "固件基于 firewall4：lan zone 的 input/output/forward 均 ACCEPT，wan zone input/forward REJECT、output ACCEPT，并启用 IPv4 masquerade 与 mtu_fix。配置中 fullcone=1，软件和硬件 flow offloading 默认均为 0；同时预装 MediaTek HNAT、WED、TurboACC、MTK HQoS/eQoS。加速、代理、统计和 SQM/限速可能互相影响，性能排障时应一次只启用一种路径并记录 nft/route 状态。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "firewall4",
        "fullcone",
        "HNAT",
        "WED",
        "TurboACC"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-03",
      "title": "C2000MAX 无线驱动与默认生成逻辑",
      "text": "镜像同时含 kmod-mt7993、kmod-mt_wifi7 和厂商 mtwifi 配置层。mtwifi 默认生成脚本会为 2.4G/5G/6G 设置 ImmortalWrt SSID、US 国家码、100% txpower，5G/6G 使用 EHT160，初始生成逻辑的 encryption 为 none；但马野教程称实机 Wi-Fi 密码为 admin，说明首次启动或设备环境还有覆盖。以实机 /etc/config/wireless 为准，并把 country 改为实际使用国家/地区。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "mt7993",
        "WiFi7",
        "EHT160",
        "无线",
        "配置"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-04",
      "title": "C2000MAX 预装的蜂窝与代理组件",
      "text": "镜像预装 qmodem-next、ubus-at-daemon、at-webserver、quectel-CM-5G-M、QMI/MBIM/NCM/RNDIS/串口驱动、MHI/PCIe 驱动、短信转发；也预装 sing-box 与 HomeProxy。它适合蜂窝模组管理和代理分流，但 qmodem、quectel-CM、ModemManager 类工具不应同时抢占同一模组；HomeProxy/sing-box、PBR、mwan 与硬件加速并用时要检查 mark 和路由表。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "5G",
        "qmodem",
        "QMI",
        "MBIM",
        "MHI",
        "HomeProxy",
        "sing-box"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-05",
      "title": "C2000MAX 默认启用的管理服务风险",
      "text": "镜像默认启用 Dropbear、uhttpd、ttyd、SFTP、at-webserver、ubus-at-daemon 等服务。Dropbear 绑定 lan，允许密码和 root 密码登录；uhttpd 同时监听 80/443，但 redirect_https=0；root 默认密码是 admin。虽然标准防火墙不允许 WAN input，若用户把蜂窝/上联误并入 lan 或修改 zone，管理服务可能暴露。建议改强密码、关闭不用的 ttyd/AT Web/SFTP，并启用 HTTPS 管理。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "Dropbear",
        "ttyd",
        "uhttpd",
        "默认服务",
        "安全"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-06",
      "title": "C2000MAX 软件源与内核模块版本风险",
      "text": "固件的 distfeeds 原始地址指向 ImmortalWrt 24.10-SNAPSHOT，首次启动的中文默认脚本会把域名替换为 https://mirrors.vsean.net/openwrt。snapshot 仓库会滚动，而本镜像内核固定为 6.6.94；较新的仓库已经出现不同内核 ABI，因此后续安装 kmod 很可能报 kernel dependency mismatch。不要强装，应使用与镜像同批的软件源/包缓存，或重刷作者提供的完整新镜像。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "opkg",
        "软件源",
        "snapshot",
        "kmod",
        "ABI"
      ]
    },
    {
      "id": "upload-20260803-7682e618b4-07",
      "title": "C2000MAX 镜像内可验证的文件哈希",
      "text": "本地包关键 SHA-256：镜像 f20a5011856d163233dd3b3fc4f1c30a59b544841ff09a09ffc7fff5fc208efd；刷机说明 dd2f987bca38faaed87d55bf6b5edc822f3c653f25978f5dd3362970774d5251；Rufus.exe abbf04d50a44a9612c027fc8072f6da67f5bcda2b826f1f852c9c24d7a1fcdff；DiskGenius EXE 736cda5b2775ef1e9b3c1aca74c6bb2adfe737d001dcd935bcbe8ee62958ebbb。哈希只能确认文件一致，不能替代对第三方可执行文件的信任与安全扫描。来源：local-source://C2000MAX-MaYe-package；作者：马野。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/043fe34d-ee51-49eb-aec0-abc970566032-c2000max-maye-part-03-of-03.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "C2000MAX",
        "SHA256",
        "Rufus",
        "DiskGenius",
        "完整性"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-01",
      "title": "鲲鹏无限公司与品牌",
      "text": "鲲鹏无限的公司主体为深圳鲲鹏无限科技有限公司，品牌英文名为 NRadio。官方帮助中心称公司创立于 2016 年，是国家高新技术企业和深圳专精特新企业，定位为 5G 无线宽带产品专业厂商。\n\n原条目 ID：company-001\n来源：https://help.nradiowifi.com/\n来源类型：official_help\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：公司、品牌、NRadio、鲲鹏无限",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "公司",
        "品牌",
        "NRadio",
        "鲲鹏无限"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-02",
      "title": "鲲鹏无限团队与创始人介绍",
      "text": "官方帮助中心称，鲲鹏无限核心团队成员来自 TP-LINK、华为、中兴、极路由等通信品牌厂商；创始人张利鹏毕业于清华大学计算机系，并在通信行业深耕十年以上。\n\n原条目 ID：company-002\n来源：https://help.nradiowifi.com/\n来源类型：official_help\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：创始人、张利鹏、团队、公司介绍",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "创始人",
        "张利鹏",
        "团队",
        "公司介绍"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-03",
      "title": "鲲鹏无限主要业务",
      "text": "鲲鹏无限主要提供 4G 和 5G 无线宽带产品，覆盖便携旅行和固定上网两类形态，强调无需铺设传统有线宽带、部署灵活和随用随开。\n\n原条目 ID：company-003\n来源：https://help.nradiowifi.com/\n来源类型：official_help\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：业务、无线宽带、5G CPE、免拉线",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "业务",
        "无线宽带",
        "5G CPE",
        "免拉线"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-04",
      "title": "鲲鹏无限官网产品分类",
      "text": "官网产品中心在 2026 年 7 月 30 日可见的产品类别包括 5G CPE、5G RedCap、全球漫游和高密度 WiFi。选型时应结合完整型号、使用地区、运营商、移动或固定场景、终端数量、网口及供电需求。\n\n原条目 ID：product-001\n来源：https://www.nradiowifi.com/chanpin/\n来源类型：official_web\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：产品中心、产品分类、选型",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "产品中心",
        "产品分类",
        "选型"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-05",
      "title": "C8 系列代表型号",
      "text": "官网在 2026 年 7 月 30 日可见的 C8 系列代表型号包括 C8-788、C8-618、C8-668GL 和 C8-688。相近名称可能对应不同芯片、地区版本、卡槽、频段或接口，回答参数时必须使用完整型号后缀。\n\n原条目 ID：product-002\n来源：https://www.nradiowifi.com/chanpin/fengwozuwang/\n来源类型：official_web\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：5G CPE、C8-788、C8-618、C8-668GL、C8-688",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "5G CPE",
        "C8-788",
        "C8-618",
        "C8-668GL",
        "C8-688"
      ]
    },
    {
      "id": "upload-20260803-6fcd6169a1-06",
      "title": "C2000 与 C5800 系列代表型号",
      "text": "官网在 2026 年 7 月 30 日可见 C2000 MAX、C2000-518、C2000-500、C5800-668GL、C5800-688 和 C5800-650。C2000 系列包含 Mini 5G CPE，C5800 系列包含企业级四卡槽 5G CPE；不同后缀的芯片和配置不可混用。\n\n原条目 ID：product-003\n来源：https://www.nradiowifi.com/chanpin/fengwozuwang/\n来源类型：official_web\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high\n标签：5G CPE、C2000 MAX、C2000、C5800、企业网络",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/d0b56767-711e-4de2-b934-1035c578a401-nradio-legacy-part-01-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "5G CPE",
        "C2000 MAX",
        "C2000",
        "C5800",
        "企业网络"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-01",
      "title": "NBCPE、NBPCE 与户外版代表型号",
      "text": "官网在 2026 年 7 月 30 日可见 NBCPE-668GL、NBPCE-688、NBPCE-650 等 NB68 与 AK68 组合形态，以及 AK68-788 户外版。不同组合和后缀对应的地区、芯片或配置不同，不能视为同一型号。原条目 ID：product-004；来源：https://www.nradiowifi.com/chanpin/fengwozuwang/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high；标签：NBCPE、NBPCE、NB68、AK68、户外CPE。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "NBCPE",
        "NBPCE",
        "NB68",
        "AK68",
        "户外CPE",
        "型号区别",
        "官网产品"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-02",
      "title": "RedCap、Nano CPE 与随身 WiFi 型号",
      "text": "官网在 2026 年 7 月 30 日可见 A8-510 RedCap 5G 移动路由器 CPE、DD-510 Nano 5G CPE、CC-500 与 CC-500 Pro 随身 WiFi，以及 TT-500、TK-500 随身快充 WiFi。原条目 ID：product-005；来源：https://www.nradiowifi.com/chanpin/qiyezuwang/1/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high；标签：RedCap、A8-510、DD-510、随身WiFi、便携。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "RedCap",
        "A8-510",
        "DD-510",
        "随身WiFi",
        "便携",
        "CC-500",
        "TT-500",
        "TK-500",
        "官网产品"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-03",
      "title": "全球漫游与高密度 WiFi 产品",
      "text": "官网在 2026 年 7 月 30 日可见 CC-100GL、TT-100GL、TK-100GL 等全球漫游便携产品，以及 E2000-R 高密度无线接入点和 N6700 AX6000 Wi-Fi 6 四频缓存路由器。全球漫游的实际国家、频段、运营商、套餐和资费应按具体型号及当前服务说明确认。原条目 ID：product-006；来源：https://www.nradiowifi.com/chanpin/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high；标签：全球漫游、高密度WiFi、CC-100GL、E2000-R、N6700。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "全球漫游",
        "高密度WiFi",
        "CC-100GL",
        "E2000-R",
        "N6700",
        "AX6000",
        "Wi-Fi 6",
        "官网产品"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-04",
      "title": "张导严选小店抖音账号",
      "text": "用户提供的短链接解析为“张导严选小店”，抖音号为 70326957594，页面标注为店铺账号，IP 属地广东。该账号可作为选品与交易入口；价格、库存、优惠、发货和售后以当前商品页及订单页面显示为准。原条目 ID：account-001；来源：https://v.douyin.com/IPb2vXHhDqs/；来源类型：douyin_profile；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium_high；标签：抖音、张导严选小店、店铺、购买渠道。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "抖音",
        "张导严选小店",
        "店铺",
        "购买渠道",
        "抖音号70326957594",
        "IP属地广东"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-05",
      "title": "鲲鹏张导抖音账号",
      "text": "用户提供的短链接解析为“鲲鹏张导”，抖音号为 kpzd，IP 属地广东。核对时的公开简介为“鲲鹏CEO张导：清华本硕｜新疆放羊娃”，账号内容围绕 5G 免拉线网络、产品和使用场景展开。原条目 ID：account-002；来源：https://v.douyin.com/SkNGZ72_cAs/；来源类型：douyin_profile；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium_high；标签：抖音、鲲鹏张导、张导、kpzd。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "抖音",
        "鲲鹏张导",
        "张导",
        "kpzd",
        "CEO",
        "5G免拉线"
      ]
    },
    {
      "id": "upload-20260803-d72682beae-06",
      "title": "鲲鹏张导公开视频内容主题",
      "text": "公开可检索作品涉及 NBCPE、C2000 MAX、DD 等产品在车辆、房车、偏远作业区、展会直播、人群密集场所和租房场景中的应用，也包括信号寻找、设备对比、产品拆解、刷机和用户共创。具体视频中的测速、信号或场景效果对应当时的设备、位置和网络条件。原条目 ID：content-001；来源：https://jingxuan.douyin.com/m/video/7632271688436043059；来源类型：douyin_video；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium；标签：使用场景、NBCPE、C2000 MAX、DD、公开视频。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/a98a89a2-27e4-41ff-9a8f-8efb81cf8042-nradio-legacy-part-02-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium",
      "tags": [
        "使用场景",
        "NBCPE",
        "C2000 MAX",
        "DD",
        "公开视频",
        "抖音",
        "车辆",
        "房车",
        "偏远作业区",
        "展会直播",
        "人群密集",
        "租房"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-01",
      "title": "C8-660 开放刷机信息",
      "text": "鲲鹏张导的公开视频曾介绍 C8-660 的开放刷机和社区共创策略，并邀请开源社区参与适配。这项信息针对 C8-660 及视频发布时的策略；其他型号是否支持刷机，应根据对应硬件版本和当前固件资料确认。原条目 ID：policy-001；来源：https://jingxuan.douyin.com/m/video/7298330506465119551；来源类型：douyin_video；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium",
      "tags": [
        "C8-660",
        "开放刷机",
        "开源",
        "社区共创"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-02",
      "title": "什么是 5G CPE",
      "text": "5G CPE 接收运营商的 5G 或 4G 蜂窝网络，再通过 WiFi 或网口为手机、电脑、摄像头等终端提供网络。它适合不方便安装有线宽带、需要临时网络、经常移动或希望快速部署网络的场景。原条目 ID：faq-001；来源：https://help.nradiowifi.com/；来源类型：official_help；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "FAQ",
        "5G CPE",
        "原理",
        "无线宽带"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-03",
      "title": "5G CPE 选型前需要确认的信息",
      "text": "推荐 5G CPE 前，应确认使用国家、城市和具体区域，运营商与 SIM 卡套餐，固定或移动使用，室内或户外，同时接入设备数，以及是否需要 2.5G 网口、双卡或多卡、全球漫游、电池、快充、外置天线、户外安装或开放刷机，并了解预算范围。原条目 ID：faq-002；来源：https://www.nradiowifi.com/chanpin/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "FAQ",
        "选型",
        "需求收集",
        "导购"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-04",
      "title": "鲲鹏产品可能适用的场景",
      "text": "官网与鲲鹏张导的公开视频涉及家庭或出租屋免拉线宽带、车辆和房车网络、展会或户外直播、偏远作业区、旅行随身网络和企业多终端接入。实际选型需要结合所在地信号、运营商、终端数、移动性、接口、天线和供电条件。原条目 ID：faq-003；来源：https://www.nradiowifi.com/chanpin/；来源类型：official_web；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium_high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "FAQ",
        "使用场景",
        "家庭网络",
        "房车",
        "直播",
        "企业网络"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-05",
      "title": "同一地点不同设备速度不同的原因",
      "text": "同一地点的不同设备可能因蜂窝频段和载波聚合能力、芯片与天线设计、SIM 卡套餐或限速策略、连接基站、设备摆放遮挡以及测试时网络拥塞程度不同而出现速度差异。公平比较应尽量使用同一 SIM 卡、同一位置、相近时间和同一测速服务器。原条目 ID：faq-004；来源：https://help.nradiowifi.com/；来源类型：official_help；原上传者：FallaxAura；核验日期：2026-07-30；可信度：medium_high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "FAQ",
        "测速",
        "信号",
        "速度差异",
        "排障"
      ]
    },
    {
      "id": "upload-20260803-51091c0fcc-06",
      "title": "免拉线宽带与有线宽带的区别",
      "text": "免拉线宽带的主要优势是部署灵活，实际速度和稳定性会随信号、基站容量、蜂窝频段、套餐和环境变化。有线宽带通常更稳定；选择哪种方案应结合安装条件、移动需求、成本和当地网络质量。原条目 ID：faq-005；来源：https://help.nradiowifi.com/；来源类型：official_help；原上传者：FallaxAura；核验日期：2026-07-30；可信度：high。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/89617f5d-a85b-4a2f-a3b2-af8a5a8b5189-nradio-legacy-part-03-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "FAQ",
        "免拉线",
        "有线宽带",
        "稳定性"
      ]
    },
    {
      "id": "upload-20260803-d2917b27a0-01",
      "title": "全球旅行多达 165 个国家的含义",
      "text": "官方帮助中心使用过“海外旅行商务多达 165 个国家可以做到开机就上网”的宣传表述。具体可用国家、蜂窝频段、合作运营商、漫游套餐、资费和公平使用规则会随产品及服务变化，出行前应按目的地和完整型号查看最新说明。\n原条目 ID：faq-006\n来源：https://help.nradiowifi.com/\n来源类型：official_help\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/311a1b7b-2de7-4281-b24d-e1bfa350b5ee-nradio-legacy-part-04-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "FAQ",
        "全球漫游",
        "165个国家",
        "旅行网络"
      ]
    },
    {
      "id": "upload-20260803-d2917b27a0-02",
      "title": "价格、库存和活动信息怎么确认",
      "text": "产品价格、库存、优惠、发货时间和活动规则应以查询当时的官网商城、官方店铺、直播间或订单页面为准。历史视频中的粉丝价、首发价和限时活动只代表当时信息。\n原条目 ID：faq-007\n来源：https://v.douyin.com/IPb2vXHhDqs/\n来源类型：douyin_profile\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：medium_high",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/311a1b7b-2de7-4281-b24d-e1bfa350b5ee-nradio-legacy-part-04-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "medium_high",
      "tags": [
        "FAQ",
        "价格",
        "库存",
        "活动",
        "发货"
      ]
    },
    {
      "id": "upload-20260803-d2917b27a0-03",
      "title": "产品参数、图片和测试数据的适用条件",
      "text": "官网说明产品图片、软件界面和实验室数据可能因产品版本、批次、生产供应、软件版本、使用条件和环境不同而变化，最终以实物和实际使用情况为准。回答具体参数时应使用完整型号和对应资料，不能用相近型号的数据代替。\n原条目 ID：risk-001\n来源：https://www.nradiowifi.com/article/207.html\n来源类型：official_web\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/311a1b7b-2de7-4281-b24d-e1bfa350b5ee-nradio-legacy-part-04-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "参数",
        "产品图片",
        "实验室数据",
        "型号",
        "适用条件"
      ]
    },
    {
      "id": "upload-20260803-d2917b27a0-04",
      "title": "小助理企业微信被封临时联系方式",
      "text": "2026年7月29日，小助理企业微信被封，临时可通过QQ联系。恢复后恢复微信交流。QQ号：猫猫：1403713828，林林：242150291，好好：3293869279。\n原条目 ID：upload-20260730-27d9403f68-01\n来源：https://github.com/NRadio-Bot/nradio-platform/blob/main/knowledge-base/sources/uploads/2026-07/6d5727f8-5810-4397-9898-98c9f6991beb-未命名.txt\n来源类型：user_upload\n原上传者：FallaxAura\n核验日期：2026-07-30\n可信度：high",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/311a1b7b-2de7-4281-b24d-e1bfa350b5ee-nradio-legacy-part-04-of-04.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "企业微信",
        "QQ",
        "联系方式",
        "临时",
        "2026-07-29"
      ]
    },
    {
      "id": "upload-20260803-358cf6d45d-01",
      "title": "OpenWrt 官方支持渠道如何选择",
      "text": "设备安装与用户配置优先查 OpenWrt Wiki、Table of Hardware/设备页和官方论坛；可复现的软件缺陷提交到对应 GitHub 仓库，开发讨论和补丁走邮件列表。提问时提供设备完整型号/版本、发行版、`ubus call system board`、复现步骤、期望与实际结果、日志和已做测试，删除密码/私钥但不要删除关键错误上下文。（核验时间：2026-08-03；来源：https://openwrt.org/support）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/7b62bce8-4a2d-48c8-902a-a63a60c43b81-openwrt-ecosystem-part-01-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "社区",
        "OpenWrt官方论坛",
        "GitHub",
        "支持",
        "提问"
      ]
    },
    {
      "id": "upload-20260803-358cf6d45d-02",
      "title": "OpenWrt GitHub 仓库的职责划分",
      "text": "`openwrt/openwrt` 负责基础系统、target、内核与构建；`openwrt/packages` 负责大量用户软件；`openwrt/luci` 负责 Web 界面；`openwrt/routing` 负责 mwan3、路由协议等。插件页面坏不一定是 LuCI 核心问题，kmod 不加载也不该报给插件作者。先找到包 Makefile 中的 PKG_SOURCE 和 maintainer，再去正确仓库。（核验时间：2026-08-03；来源：https://github.com/openwrt/openwrt）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/7b62bce8-4a2d-48c8-902a-a63a60c43b81-openwrt-ecosystem-part-01-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "社区",
        "GitHub",
        "openwrt",
        "packages",
        "luci",
        "routing"
      ]
    },
    {
      "id": "upload-20260803-358cf6d45d-03",
      "title": "官方 Forum 与 Reddit 的证据等级",
      "text": "OpenWrt Forum 是官方社区，常有维护者参与，但帖子仍可能过时或针对特定 snapshot；`r/openwrt` 是非官方 subreddit，适合发现思路和用户体验，开发者不会保证看到。任何复制命令都要核对发布日期、版本、target 和后续回复，最终以设备页、当前源码和本机日志验证。（核验时间：2026-08-03；来源：https://www.reddit.com/r/openwrt/）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/7b62bce8-4a2d-48c8-902a-a63a60c43b81-openwrt-ecosystem-part-01-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "社区",
        "OpenWrtForum",
        "Reddit",
        "证据"
      ]
    },
    {
      "id": "upload-20260803-358cf6d45d-04",
      "title": "恩山无线论坛适合查什么",
      "text": "恩山无线论坛对中国市场路由器拆机、TTL 点位、Breed/U-Boot、运营商光猫、国产 SoC 和第三方固件经验非常丰富，适合发现设备线索。但附件、网盘固件和一键工具的源码、版本、哈希与安全性常不透明；应先找原作者主题、交叉验证硬件版本，备份 bootloader/factory/calibration，再决定是否使用。（核验时间：2026-08-03；来源：https://www.right.com.cn/）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/7b62bce8-4a2d-48c8-902a-a63a60c43b81-openwrt-ecosystem-part-01-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "社区",
        "恩山",
        "right",
        "第三方固件",
        "刷机"
      ]
    },
    {
      "id": "upload-20260803-358cf6d45d-05",
      "title": "ImmortalWrt 社区与 OpenWrt 上游的关系",
      "text": "ImmortalWrt 是面向中国用户的 OpenWrt 分支，增加设备、包、本地化和部分不易上游的优化。问题若只在 ImmortalWrt 或其 MTK/代理组件出现，应查 ImmortalWrt GitHub Discussions/Issues、Matrix/Telegram 支持渠道；上游 OpenWrt 文档仍适用于大量基础机制，但不能假设固件、kmod、feed 或 sysupgrade 与上游互换。（核验时间：2026-08-03；来源：https://github.com/immortalwrt/immortalwrt）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/7b62bce8-4a2d-48c8-902a-a63a60c43b81-openwrt-ecosystem-part-01-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "社区",
        "ImmortalWrt",
        "OpenWrt",
        "分支",
        "支持"
      ]
    },
    {
      "id": "upload-20260803-358cf6d45d-06",
      "title": "选择插件前的六项兼容检查",
      "text": "安装前确认发行版与版本、CPU 架构、包管理器 opkg/apk、firewall3/4、内核 ABI、维护者支持分支；再核对依赖、可写空间、RAM 和是否与现有 DNS/PBR/代理冲突。优先官方 feed，其次项目作者签名 release，最后才是论坛附件。保存插件版本、来源 URL、配置目录和回滚命令。（核验时间：2026-08-03；来源：https://openwrt.org/docs/guide-user/additional-software/managing_packages）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/7b62bce8-4a2d-48c8-902a-a63a60c43b81-openwrt-ecosystem-part-01-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "兼容性",
        "opkg",
        "apk",
        "fw4",
        "kmod"
      ]
    },
    {
      "id": "upload-20260803-358cf6d45d-07",
      "title": "luci-app-* 与后台服务的关系",
      "text": "多数 `luci-app-foo` 只是配置界面，真正功能来自 `foo`、内核模块或脚本；有些包还需 `luci-i18n-foo-zh-cn`。只装 UI 会出现 RPC/文件不存在，只装后台则不会出现菜单。必须从同一分支/仓库成套安装，升级时避免 LuCI 前端比 UCI schema 或 rpcd 后端更新得更快。（核验时间：2026-08-03；来源：https://github.com/openwrt/luci）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/7b62bce8-4a2d-48c8-902a-a63a60c43b81-openwrt-ecosystem-part-01-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "LuCI",
        "luci-app",
        "后台",
        "rpcd"
      ]
    },
    {
      "id": "upload-20260803-05e89ba771-01",
      "title": "adblock、adblock-fast 与 AdGuard Home 怎么选",
      "text": "adblock/adblock-fast 更贴近 OpenWrt，可与 dnsmasq/Unbound/SmartDNS 协作，资源开销通常较低；AdGuard Home 提供独立 Web UI、统计和过滤能力，但占内存更高且会竞争 53 端口。只选一个主过滤路径，合理控制列表规模并维护 allowlist；DNS 过滤不能代替浏览器内容过滤。来源：https://openwrt.org/docs/guide-user/services/ad-blocking 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/9f8dcaf7-240c-4cf2-beb0-33324bc2c841-openwrt-ecosystem-part-02-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "adblock",
        "AdGuardHome",
        "DNS过滤"
      ]
    },
    {
      "id": "upload-20260803-05e89ba771-02",
      "title": "MosDNS、SmartDNS、dnsmasq 与加密 DNS 的组合原则",
      "text": "dnsmasq 适合 DHCP、本地域名和缓存入口；MosDNS/SmartDNS/Unbound/https-dns-proxy 可承担分流、测速或加密上游。稳定组合只有一个 LAN:53 入口，后端监听 loopback 非 53 端口，并明确 bootstrap DNS，防止循环依赖。代理插件若也劫持 DNS，应把整条调用链画出来再配置。来源：https://github.com/sbwml/luci-app-mosdns 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/9f8dcaf7-240c-4cf2-beb0-33324bc2c841-openwrt-ecosystem-part-02-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "MosDNS",
        "SmartDNS",
        "dnsmasq",
        "DoH",
        "DNS"
      ]
    },
    {
      "id": "upload-20260803-05e89ba771-03",
      "title": "DDNS 插件的正确使用边界",
      "text": "ddns-scripts 每个 section 通常维护一个主机名和一种地址族。先确认 WAN 获取的是可入站公网 IPv4 或有效 IPv6；CGNAT 下 DDNS 只能发布不可直连的地址，不能创造端口映射。使用 interface、web 或 script 取地址时要防止发布 VPN/ULA/私网地址，并查 `logread -e ddns` 与提供商返回码。来源：https://openwrt.org/docs/guide-user/base-system/ddns 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/9f8dcaf7-240c-4cf2-beb0-33324bc2c841-openwrt-ecosystem-part-02-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "DDNS",
        "公网IP",
        "CGNAT",
        "IPv6"
      ]
    },
    {
      "id": "upload-20260803-05e89ba771-04",
      "title": "banIP 与普通防火墙的分工",
      "text": "banIP 把地址列表加载到 nft set 并生成规则，适合地区/威胁源批量拦截；基础 zone、端口和服务访问控制仍应写在 firewall4。大列表会占 RAM、延长 reload，误封 DNS/CDN/云服务也很常见。先以 report/log 模式验证，并给管理地址、VPN peer 和必要服务设置 allowlist。来源：https://openwrt.org/docs/guide-user/services/start 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/9f8dcaf7-240c-4cf2-beb0-33324bc2c841-openwrt-ecosystem-part-02-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "banIP",
        "nftables",
        "防火墙",
        "黑名单"
      ]
    },
    {
      "id": "upload-20260803-05e89ba771-05",
      "title": "SQM/CAKE 的进阶玩法",
      "text": "先关闭 flow offload，在真实瓶颈接口设置略低于可持续带宽的上下行；PPPoE/VLAN/蜂窝链路要配置开销。CAKE 的 besteffort、diffserv4、dual-srchost/dsthost 等选项影响公平性和分类，只有在基线稳定后再调。用满载上下行同时测延迟，而不是只看空载测速。来源：https://openwrt.org/docs/guide-user/network/traffic-shaping/sqm_configuration 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/9f8dcaf7-240c-4cf2-beb0-33324bc2c841-openwrt-ecosystem-part-02-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "SQM",
        "CAKE",
        "DiffServ",
        "Bufferbloat"
      ]
    },
    {
      "id": "upload-20260803-05e89ba771-06",
      "title": "mwan3 的进阶策略设计",
      "text": "member 的 metric 决定优先级、weight 决定同 metric 新连接分配比例；policy 决定组合，rule 决定哪些流量使用 policy。给支付、游戏、VoIP、VPN 和入站回程配置线路粘滞，给大流量下载做均衡。探测目标、DNS 和路由器自身流量也必须能够绑定正确 WAN。来源：https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/9f8dcaf7-240c-4cf2-beb0-33324bc2c841-openwrt-ecosystem-part-02-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "mwan3",
        "多WAN",
        "策略",
        "负载均衡"
      ]
    },
    {
      "id": "upload-20260803-05e89ba771-07",
      "title": "PBR 的域名策略为什么会漂移",
      "text": "域名会解析到 CDN 多地址并随时间改变，PBR 需要 dnsmasq nft set/ipset 或解析器把结果动态加入集合。客户端若使用 DoH、硬编码 DNS 或 QUIC，路由器可能看不到域名；同 IP 也可能承载多个域名。重要策略优先使用源设备/网段和明确 IP/CIDR，域名规则作为便利层。来源：https://openwrt.org/docs/guide-user/network/routing/pbr 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/9f8dcaf7-240c-4cf2-beb0-33324bc2c841-openwrt-ecosystem-part-02-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "PBR",
        "域名",
        "nftset",
        "DoH",
        "CDN"
      ]
    },
    {
      "id": "upload-20260803-8e61fc7e9d-01",
      "title": "usteer 与 DAWN 只能选择一个",
      "text": "usteer 与 DAWN 不能同时启用。两者都根据 802.11k/v 信息和信号/负载向客户端提出漫游建议，同时启用会产生相互矛盾的 steering。OpenWrt 24.10 常需完整 wpad 才支持 k/r/v。部署时应先统一 SSID、加密、VLAN 和 802.11r，再用默认或温和阈值部署 steering；客户端最终仍可忽略建议。来源：https://openwrt.org/docs/guide-user/network/wifi/roaming 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/98a8f713-9a54-4508-acee-89483d0eb02f-openwrt-ecosystem-part-03-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "OpenWrt",
        "插件",
        "usteer",
        "DAWN",
        "80211k",
        "80211v",
        "漫游"
      ]
    },
    {
      "id": "upload-20260803-8e61fc7e9d-02",
      "title": "usteer 的诊断接口",
      "text": "usteer 的诊断接口：使用 `ubus call usteer local_info`、`remote_hosts`、`remote_info`、`get_clients` 查看本地/远端 AP、负载、噪声和客户端能力。若 remote_hosts 为空，检查各 AP 的 network 配置、二层/三层可达性和防火墙；若有邻居但不漫游，检查客户端是否支持 BSS Transition、信号差阈值与目标 AP 是否确实更好。来源：https://openwrt.org/docs/guide-user/network/wifi/usteer 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/98a8f713-9a54-4508-acee-89483d0eb02f-openwrt-ecosystem-part-03-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "OpenWrt",
        "插件",
        "usteer",
        "ubus",
        "漫游",
        "诊断"
      ]
    },
    {
      "id": "upload-20260803-8e61fc7e9d-03",
      "title": "WireGuard、Tailscale、ZeroTier 的选择",
      "text": "WireGuard、Tailscale、ZeroTier 的选择：WireGuard 自建最轻量，拓扑和密钥完全可控，但需自己处理公网入口、路由与密钥；Tailscale 基于 WireGuard，控制面和 NAT 穿透更易用，可做 subnet router/exit node；ZeroTier 提供虚拟二层/三层网络和集中授权。无论哪种，加入虚拟网后都要单独设计 firewall zone、路由宣告和管理权限。来源：https://openwrt.org/docs/guide-user/services/vpn/tailscale/start 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/98a8f713-9a54-4508-acee-89483d0eb02f-openwrt-ecosystem-part-03-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "OpenWrt",
        "插件",
        "WireGuard",
        "Tailscale",
        "ZeroTier",
        "VPN"
      ]
    },
    {
      "id": "upload-20260803-8e61fc7e9d-04",
      "title": "Tailscale subnet router/exit node 的进阶检查",
      "text": "Tailscale subnet router/exit node 的进阶检查：OpenWrt 宣告 LAN 网段后，需要在控制面批准 route，并允许 tailscale zone 到 LAN forwarding；使用 exit node 还要处理默认路由、DNS 和 MTU。若只有路由器自身能通而 LAN 客户端不通，检查 forwarding、NAT 和 LAN 客户端默认网关。不要把管理网段无差别暴露给 tailnet 全体成员。来源：https://openwrt.org/docs/guide-user/services/vpn/tailscale/start 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/98a8f713-9a54-4508-acee-89483d0eb02f-openwrt-ecosystem-part-03-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "OpenWrt",
        "插件",
        "Tailscale",
        "SubnetRouter",
        "ExitNode"
      ]
    },
    {
      "id": "upload-20260803-8e61fc7e9d-05",
      "title": "ZeroTier 版本升级后的 UCI schema 差异",
      "text": "ZeroTier 版本升级后的 UCI schema 差异：ZeroTier 1.14.1 前后 OpenWrt UCI 示例结构发生变化，旧教程的 `list join` 与新 `config network` 写法不能机械混用。以当前包自带 `/etc/config/zerotier` 和官方文档为准，升级前保存 network ID、identity 和授权状态；虚拟接口要加入单独 firewall zone。来源：https://openwrt.org/docs/guide-user/services/vpn/zerotier 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/98a8f713-9a54-4508-acee-89483d0eb02f-openwrt-ecosystem-part-03-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "OpenWrt",
        "插件",
        "ZeroTier",
        "UCI",
        "网络"
      ]
    },
    {
      "id": "upload-20260803-8e61fc7e9d-06",
      "title": "OpenClash 的定位与兼容风险",
      "text": "OpenClash 的定位与兼容风险：OpenClash 是基于 Mihomo/Clash 的第三方 OpenWrt 客户端，功能丰富，依赖 dnsmasq-full、TUN/TProxy、iptables/nft 兼容组件和自身核心。它不属于 OpenWrt 官方 feed；安装必须按项目 release 匹配 fw4、CPU 架构与内核模块。升级前导出配置，不能与其他透明代理同时接管 DNS、默认路由和 fwmark。来源：https://github.com/vernesong/OpenClash 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/98a8f713-9a54-4508-acee-89483d0eb02f-openwrt-ecosystem-part-03-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "OpenWrt",
        "插件",
        "OpenClash",
        "Mihomo",
        "TProxy",
        "第三方"
      ]
    },
    {
      "id": "upload-20260803-8e61fc7e9d-07",
      "title": "PassWall 的定位与依赖管理",
      "text": "PassWall 的定位与依赖管理：PassWall 是第三方代理管理插件，主仓库和 packages feed 分开，协议核心与 LuCI 版本需要成套。安装前确认所用 OpenWrt/ImmortalWrt 分支、架构、iptables/nftables 路径和核心来源；遇到依赖缺失应按项目 feed 编译/安装，不能从不同固件仓库拼包。与 OpenClash/HomeProxy/PBR 并用极易冲突。来源：https://github.com/Openwrt-Passwall/openwrt-passwall 核验日期：2026-08-03",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/98a8f713-9a54-4508-acee-89483d0eb02f-openwrt-ecosystem-part-03-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "OpenWrt",
        "插件",
        "PassWall",
        "代理",
        "第三方",
        "feed"
      ]
    },
    {
      "id": "upload-20260803-9cfe347d5f-01",
      "title": "HomeProxy 与 sing-box 的版本绑定",
      "text": "HomeProxy 是 ImmortalWrt 面向 ARM64/AMD64 的 sing-box 管理平台。sing-box 配置格式和弃用项变化较快，HomeProxy 生成器必须匹配核心版本；订阅节点变化也可能让 selector/urltest 引用失效。升级时同时检查 HomeProxy 与 sing-box changelog，先做配置校验，再切换生产流量。核验日期：2026-08-03。来源：https://github.com/immortalwrt/homeproxy",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/41dd67bd-c746-43f4-83bb-5438b4f2ba8d-openwrt-ecosystem-part-04-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "HomeProxy",
        "sing-box",
        "版本",
        "配置"
      ]
    },
    {
      "id": "upload-20260803-9cfe347d5f-02",
      "title": "代理插件排障的最小化原则",
      "text": "代理插件排障时，先停透明代理确认原生 WAN/DNS 正常；然后只启用一个插件、一个 DNS 入口和一个默认路由接管者。记录 `ip rule`、`ip route show table all`、`nft list ruleset`、53 端口监听、插件日志与核心配置检查结果。节点连通、DNS、路由和 TProxy 是四个独立层，不要只凭“订阅更新成功”判断服务可用。核验日期：2026-08-03。来源：https://github.com/vernesong/OpenClash",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/41dd67bd-c746-43f4-83bb-5438b4f2ba8d-openwrt-ecosystem-part-04-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "透明代理",
        "排障",
        "DNS",
        "TProxy",
        "fwmark"
      ]
    },
    {
      "id": "upload-20260803-9cfe347d5f-03",
      "title": "Samba4 与 ksmbd 怎么选",
      "text": "Samba4 功能和兼容性更完整、资源占用较高；ksmbd 是内核 SMB3 服务，较轻但功能较少。外置盘先稳定挂载，再创建专用用户、设置目录权限和 SMB 密码；不要开放到 WAN。高并发、重要数据和 Time Machine 场景优先评估完整 Samba，低资源简单共享可考虑 ksmbd。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/services/nas/cifs.server",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/41dd67bd-c746-43f4-83bb-5438b4f2ba8d-openwrt-ecosystem-part-04-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "Samba",
        "ksmbd",
        "NAS",
        "SMB"
      ]
    },
    {
      "id": "upload-20260803-9cfe347d5f-04",
      "title": "Docker/Podman 在 OpenWrt 上的适用边界",
      "text": "容器适合 x86/高内存 ARM 和可靠外置存储，不适合小闪存路由器。把容器 root、volume 与日志放到 ext4/btrfs 数据盘，限制日志和内存；容器 bridge、macvlan 和端口发布会与 firewall4、VLAN、PBR 交互。路由核心功能不宜全部塞进容器，以免容器引擎故障导致整网失联。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/virtualization/docker_host",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/41dd67bd-c746-43f4-83bb-5438b4f2ba8d-openwrt-ecosystem-part-04-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "Docker",
        "Podman",
        "容器",
        "存储"
      ]
    },
    {
      "id": "upload-20260803-9cfe347d5f-05",
      "title": "Transmission/aria2 等下载插件的路由器负载风险",
      "text": "P2P 会制造大量连接、随机磁盘写入和 conntrack 压力，TF 卡和小内存设备容易出现 I/O wait、table full 与 OOM。把下载目录放到独立硬盘，限制并发/连接数/缓存和上传速度，配合 SQM 时预留带宽；不要让下载器写内部 overlay。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/services/start",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/41dd67bd-c746-43f4-83bb-5438b4f2ba8d-openwrt-ecosystem-part-04-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "Transmission",
        "aria2",
        "P2P",
        "下载",
        "conntrack"
      ]
    },
    {
      "id": "upload-20260803-9cfe347d5f-06",
      "title": "miniupnpd/UPnP 的安全边界",
      "text": "UPnP 允许可信 LAN 客户端动态创建端口映射，方便游戏和通信，但恶意或被入侵客户端也能开放服务。仅在明确的可信 zone 启用，限制外部端口和租期，绝不监听 WAN/访客网；CGNAT 下即使映射成功也未必能从互联网访问。高安全环境使用手工端口转发或 VPN。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/services/start",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/41dd67bd-c746-43f4-83bb-5438b4f2ba8d-openwrt-ecosystem-part-04-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "插件",
        "UPnP",
        "miniupnpd",
        "端口映射",
        "安全"
      ]
    },
    {
      "id": "upload-20260803-9cfe347d5f-07",
      "title": "irqbalance、packet steering 和硬件卸载",
      "text": "irqbalance/packet steering 尝试把网络中断和软中断分散到多核，硬件卸载绕过部分 CPU 路径。收益取决于 SoC、驱动和拓扑，盲目全开可能增加延迟或与厂商 HNAT/WED 冲突。用 `top -H`、`/proc/interrupts`、软中断和 iperf3 前后对比，单独改变一个变量。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/services/start",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/41dd67bd-c746-43f4-83bb-5438b4f2ba8d-openwrt-ecosystem-part-04-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "进阶",
        "irqbalance",
        "PacketSteering",
        "HNAT",
        "WED",
        "性能"
      ]
    },
    {
      "id": "upload-20260803-2c572fbf2c-01",
      "title": "VLAN + 多 AP + 多 SSID 的进阶架构",
      "text": "主路由负责每个 VLAN 的网关、DHCP 和 firewall，交换机/AP 上联使用 tagged trunk，各 SSID 映射到对应 VLAN，管理 VLAN 单独限制。DSA bridge-vlan 中明确每个接入口的 PVID/untagged 和 trunk 的 tagged；部署前保留一个本地 untagged 管理口，逐 VLAN 验证 DHCP、DNS、隔离和漫游。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/network/wifi/roaming",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/4d42ebad-7120-4079-84d7-1e195a8356ea-openwrt-ecosystem-part-05-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "进阶",
        "VLAN",
        "多AP",
        "多SSID",
        "Trunk",
        "DSA",
        "OpenWrt"
      ]
    },
    {
      "id": "upload-20260803-2c572fbf2c-02",
      "title": "VRRP/keepalived 双路由高可用的限制",
      "text": "两台 OpenWrt 可用 keepalived/VRRP 漂移 LAN 虚拟网关，但状态防火墙、NAT、DHCP、IPv6 PD 和连接跟踪默认不会完整同步，主备切换仍可能中断会话。先解决配置同步、WAN 独立性和 split-brain，再考虑 conntrackd；家庭环境常用双机冷备和可恢复配置更简单。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/services/start",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/4d42ebad-7120-4079-84d7-1e195a8356ea-openwrt-ecosystem-part-05-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "进阶",
        "VRRP",
        "keepalived",
        "高可用",
        "双路由",
        "OpenWrt"
      ]
    },
    {
      "id": "upload-20260803-2c572fbf2c-03",
      "title": "FRR/Babel/OLSR 等动态路由的使用场景",
      "text": "多路由、多站点或 mesh 可使用 FRR 的 OSPF/BGP、Babel 或 OLSR 自动交换前缀；单路由家庭网络通常不需要。动态路由必须限制邻居、认证和可发布前缀，避免把默认路由或管理网误传播。和 mwan3/PBR 同时使用时要规划 table、metric 和策略优先级。核验日期：2026-08-03。来源：https://github.com/openwrt/routing",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/4d42ebad-7120-4079-84d7-1e195a8356ea-openwrt-ecosystem-part-05-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "进阶",
        "FRR",
        "BGP",
        "OSPF",
        "Babel",
        "OLSR",
        "动态路由",
        "OpenWrt"
      ]
    },
    {
      "id": "upload-20260803-2c572fbf2c-04",
      "title": "collectd、vnStat、Prometheus/Telegraf 监控",
      "text": "轻量长期流量可用 vnStat，设备和接口时序指标可用 collectd/rrdtool 或 Telegraf 输出到外部数据库。路由器内部闪存不适合高频写时序数据，应写 tmpfs 后批量上传或直接远端存储；监控接口不要暴露 WAN，并限制标签基数和采样频率。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/services/start",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/4d42ebad-7120-4079-84d7-1e195a8356ea-openwrt-ecosystem-part-05-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "进阶",
        "监控",
        "collectd",
        "vnStat",
        "Telegraf",
        "Prometheus",
        "OpenWrt"
      ]
    },
    {
      "id": "upload-20260803-2c572fbf2c-05",
      "title": "自定义热插拔与 procd 服务",
      "text": "设备事件脚本放在 `/etc/hotplug.d/<subsystem>/`，长期进程应写 procd init 脚本，声明 command、respawn、file/netdev/interface trigger，而不是堆进 `rc.local`。脚本必须幂等、记录日志并对缺失设备超时；热插拔环境变量和 PATH 有限，先在日志中打印必要上下文。核验日期：2026-08-03。来源：https://github.com/openwrt/openwrt",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/4d42ebad-7120-4079-84d7-1e195a8356ea-openwrt-ecosystem-part-05-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "进阶",
        "hotplug",
        "procd",
        "init",
        "脚本",
        "自动化",
        "OpenWrt"
      ]
    },
    {
      "id": "upload-20260803-2c572fbf2c-06",
      "title": "Image Builder 预装插件比在线安装更可靠",
      "text": "小闪存、snapshot、批量设备或依赖 kmod 的插件，应在 Image Builder/源码构建时集成，使内核模块、依赖和 SquashFS 同批生成。保存 package list、feeds revision、FILES、首次启动脚本和 SHA-256。不要把含密码/订阅/私钥的配置直接烘进公开镜像。核验日期：2026-08-03。来源：https://openwrt.org/downloads",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/4d42ebad-7120-4079-84d7-1e195a8356ea-openwrt-ecosystem-part-05-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "进阶",
        "ImageBuilder",
        "插件",
        "kmod",
        "批量",
        "固件",
        "OpenWrt"
      ]
    },
    {
      "id": "upload-20260803-2c572fbf2c-07",
      "title": "社区脚本和一键包的审查清单",
      "text": "执行前下载到本地阅读，检查是否修改 distfeeds、关闭签名/TLS、使用 curl|sh、写 bootloader/factory、添加 cron/开机自启、上传遥测、保存明文凭据或执行 `rm/dd`。记录哈希和来源 commit，在测试机/备份后运行。无法审查的闭源 EXE 和网盘固件只能视为高风险第三方材料。核验日期：2026-08-03。来源：https://www.right.com.cn/",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/4d42ebad-7120-4079-84d7-1e195a8356ea-openwrt-ecosystem-part-05-of-05.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "社区",
        "一键脚本",
        "安全",
        "审查",
        "固件",
        "OpenWrt"
      ]
    },
    {
      "id": "upload-20260803-1dae6cba1c-01",
      "title": "报错：Image check failed / Invalid image type",
      "text": "该报错表示平台校验拒绝镜像，常见原因是 factory/sysupgrade 类型错、设备 profile 或硬件版本错、镜像损坏、从 swconfig 迁移 DSA 时配置不兼容。先运行 `ubus call system board`、核对下载页 target/profile 和 SHA-256，再执行 `sysupgrade -T /tmp/firmware` 查看完整前置日志。只有设备官方说明明确要求时才考虑 force；不能用强刷掩盖型号错误。（来源：https://openwrt.org/docs/guide-user/installation/generic.sysupgrade；核验日期：2026-08-03）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/048f8d73-8c0f-4068-9590-9d512f6d12c0-openwrt-errors-part-01-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "ImageCheckFailed",
        "InvalidImage",
        "sysupgrade",
        "固件"
      ]
    },
    {
      "id": "upload-20260803-1dae6cba1c-02",
      "title": "报错：Image version mismatch / Config cannot be migrated",
      "text": "这通常不是文件损坏，而是 image compat version 或网络模型发生变化，例如端口命名、DSA 迁移。应导出配置和包清单，下载正确镜像，使用不保留设置的升级方式并手工重建。`sysupgrade -n` 会清除配置，执行前必须确保有本地网线、默认地址和恢复路径；不要把旧 `/etc/config/network` 整体复制回去。（来源：https://openwrt.org/docs/guide-user/network/dsa/upgrading-to-2102；核验日期：2026-08-03）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/048f8d73-8c0f-4068-9590-9d512f6d12c0-openwrt-errors-part-01-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "VersionMismatch",
        "DSA",
        "配置迁移",
        "sysupgrade"
      ]
    },
    {
      "id": "upload-20260803-1dae6cba1c-03",
      "title": "报错：The uploaded image file does not contain a supported format",
      "text": "LuCI 无法识别上传文件时，先确认没有把 `.zip`、网页下载错误页、factory 镜像或磁盘整盘 img 当作 sysupgrade 镜像。用 `file`、`sha256sum` 和 `sysupgrade -T` 检查；浏览器下载文件尺寸异常小往往是登录页或 404。设备若要求 U-Boot、TFTP、SD 整盘写入，应按设备安装方法操作，不能从 LuCI 上传。（来源：https://openwrt.org/docs/guide-user/installation/generic.sysupgrade；核验日期：2026-08-03）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/048f8d73-8c0f-4068-9590-9d512f6d12c0-openwrt-errors-part-01-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "LuCI",
        "UnsupportedFormat",
        "固件",
        "上传"
      ]
    },
    {
      "id": "upload-20260803-1dae6cba1c-04",
      "title": "报错：not enough space in /tmp / No space left on device 上传固件失败",
      "text": "LuCI 和 sysupgrade 通常先把镜像放到 RAM-backed `/tmp`。检查 `df -h /tmp /overlay`、`free -h`、`ls -lh /tmp`；停止占内存服务并删除临时文件。低内存设备可从 URL 流式升级或用设备文档给出的低内存方案，但升级时不要靠 swap 掩盖严重内存不足，也不要把固件放到不受平台脚本支持的路径。（来源：https://openwrt.org/docs/guide-user/installation/generic.sysupgrade；核验日期：2026-08-03）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/048f8d73-8c0f-4068-9590-9d512f6d12c0-openwrt-errors-part-01-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "tmp",
        "空间不足",
        "sysupgrade",
        "RAM"
      ]
    },
    {
      "id": "upload-20260803-1dae6cba1c-05",
      "title": "报错：Failed to kill all processes / Command failed during sysupgrade",
      "text": "升级切换到 ramfs 后会终止服务并卸载文件系统；进程无法结束、外置盘忙或平台脚本 I/O 错误都可能中断。不要立刻断电，保留串口输出和完整 sysupgrade 日志，确认设备是否仍在写闪存。再次尝试前停止容器、下载、挂载和代理服务，并校验镜像；若已经无法启动，使用设备专用 recovery/TFTP/串口方案。（来源：https://openwrt.org/docs/guide-user/installation/generic.sysupgrade；核验日期：2026-08-03）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/048f8d73-8c0f-4068-9590-9d512f6d12c0-openwrt-errors-part-01-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "sysupgrade",
        "FailedToKill",
        "processes",
        "I/O"
      ]
    },
    {
      "id": "upload-20260803-1dae6cba1c-06",
      "title": "报错：Cannot satisfy dependencies / kernel is not compatible",
      "text": "安装 kmod 时该报错几乎总是正在运行的内核 ABI 与仓库包不一致，snapshot 和第三方固件最常见。记录 `uname -r`、`opkg status kernel`、release/target 和 distfeeds；使用同一构建批次的软件源，或重刷当前仓库对应镜像。不要对内核模块使用 `--force-depends`，即使文件装进去也可能无法加载、崩溃或无法重启。（来源：https://openwrt.org/faq/cannot_satisfy_dependencies；核验日期：2026-08-03）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/048f8d73-8c0f-4068-9590-9d512f6d12c0-openwrt-errors-part-01-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "kmod",
        "KernelNotCompatible",
        "依赖",
        "ABI"
      ]
    },
    {
      "id": "upload-20260803-1dae6cba1c-07",
      "title": "报错：Unknown package / package not found",
      "text": "先更新索引并确认包名、版本和架构：24.10 及更早运行 `opkg update`，25.12 及以后运行 `apk update`；查看源是否启用、URL 是否返回真实仓库、包是否为该架构构建。某些 LuCI 页面需要 `luci-app-名称`，协议还需要 `luci-proto-名称`。第三方教程里的包可能不在官方源，应去项目仓库核对支持分支，而不是随便添加陌生 feed。（来源：https://openwrt.org/docs/guide-user/additional-software/managing_packages；核验日期：2026-08-03）",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/048f8d73-8c0f-4068-9590-9d512f6d12c0-openwrt-errors-part-01-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "UnknownPackage",
        "opkg",
        "apk",
        "软件包"
      ]
    },
    {
      "id": "upload-20260803-516b935e06-01",
      "title": "报错：Signature check failed / Packages.gz signature invalid",
      "text": "先检查系统日期、时区和 NTP，再确认 distfeeds 指向正确发行版且网络没有被透明代理替换内容。清理 `/tmp/opkg-lists` 后重新更新，并对比官方仓库 URL。不要长期关闭签名校验或安装 `--force-checksum` 得到的包；第三方 feed 必须导入其公开签名密钥并确认来源。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/additional-software/opkg",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/f4a6a8e9-16f6-40f6-85d5-9a5fb15d3219-openwrt-errors-part-02-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "SignatureCheckFailed",
        "软件源",
        "签名"
      ]
    },
    {
      "id": "upload-20260803-516b935e06-02",
      "title": "报错：wget returned 4 / Connection failed 下载软件源失败",
      "text": "wget/uclient-fetch 返回网络失败时，分别检查 `ip route`、`ping` 公网 IP、`nslookup` 仓库域名、系统时间和 HTTPS。能 ping IP 不能解析是 DNS；解析正常但 TLS 失败多为时间、证书或代理；IPv6 黑洞可用 `wget -4` 验证但应修复 WAN6/PMTU。不要把镜像站域名随意替换成目录结构不兼容的源。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/additional-software/opkg",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/f4a6a8e9-16f6-40f6-85d5-9a5fb15d3219-openwrt-errors-part-02-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "wgetReturned4",
        "opkg",
        "网络",
        "DNS",
        "TLS"
      ]
    },
    {
      "id": "upload-20260803-516b935e06-03",
      "title": "报错：SSL certificate verify failed / certificate is not yet valid",
      "text": "首先运行 `date` 检查时间；路由器无 RTC 时首次启动可能停留在固件构建日期。确保 NTP 能绕过尚未启动的加密 DNS/代理完成同步，并安装正确 CA bundle。证书域名不匹配则检查 DNS 劫持、透明代理和下载 URL。`--no-check-certificate` 只能用于定位问题，不应成为长期安装方案。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/additional-software/managing_packages",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/f4a6a8e9-16f6-40f6-85d5-9a5fb15d3219-openwrt-errors-part-02-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "TLS",
        "Certificate",
        "时间",
        "NTP"
      ]
    },
    {
      "id": "upload-20260803-516b935e06-04",
      "title": "报错：Read-only file system",
      "text": "典型 SquashFS 的 `/rom` 本来只读，但 `/` 应由 overlay 提供可写层。若写 `/etc` 也报只读，检查 `mount`、`df -h`、`dmesg` 和 `logread`，可能是 overlay 尚未初始化、文件系统损坏、extroot 掉线或进入 failsafe 未执行 `mount_root`。不要用 remount 强行写 `/rom`；先恢复 overlay 或从 failsafe 修复。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/f4a6a8e9-16f6-40f6-85d5-9a5fb15d3219-openwrt-errors-part-02-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "ReadOnlyFilesystem",
        "overlay",
        "mount_root"
      ]
    },
    {
      "id": "upload-20260803-516b935e06-05",
      "title": "报错：jffs2 not ready / overlay not mounted",
      "text": "首次启动需要格式化 rootfs_data，低速闪存可能等待数分钟；持续失败则检查 mtd/UBI 分区、内核日志和镜像布局。运行 `mount`、`df -h`、`cat /proc/mtd` 或 `ubinfo -a`，确认没有刷错 NAND/NOR 镜像。不要在 overlay 初始化期间频繁断电；必要时进 failsafe 备份后 factoryreset。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/f4a6a8e9-16f6-40f6-85d5-9a5fb15d3219-openwrt-errors-part-02-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "JFFS2",
        "overlay",
        "UBI",
        "首次启动"
      ]
    },
    {
      "id": "upload-20260803-516b935e06-06",
      "title": "报错：block: extroot: UUID mismatch",
      "text": "升级后 extroot 日志出现 UUID mismatch 时，先用 `block info` 和 `uci show fstab` 确认目标分区。官方 extroot 文档建议在确认外置卷确实是原 extroot 后移除卷上的 `.extroot-uuid` 再重试。不要删除未知磁盘文件或重新格式化；先挂到临时目录备份配置并记录 UUID。核验日期：2026-08-03。来源：https://openwrt.org/docs/guide-user/additional-software/extroot_configuration",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/f4a6a8e9-16f6-40f6-85d5-9a5fb15d3219-openwrt-errors-part-02-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "extroot",
        "UUIDMismatch",
        "block-mount"
      ]
    },
    {
      "id": "upload-20260803-516b935e06-07",
      "title": "报错：mount: wrong fs type / bad superblock",
      "text": "表示内核无法按指定类型挂载，原因可能是缺少 `kmod-fs-*`、文件系统损坏、类型写错、分区仍被占用或实际是 LUKS/LVM。用 `block info`、`blkid`、`file -s` 和 dmesg 确认类型；在电脑或离线环境运行对应 fsck。不要在已挂载或正在写入的卷上直接修复文件系统。核验日期：2026-08-03。来源：https://openwrt.org/docs/techref/block_mount",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/f4a6a8e9-16f6-40f6-85d5-9a5fb15d3219-openwrt-errors-part-02-of-06.md",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-03",
      "confidence": "high",
      "tags": [
        "报错",
        "WrongFsType",
        "BadSuperblock",
        "mount",
        "存储"
      ]
    }
  ]
}
