// Generated by scripts/sync-knowledge.mjs. Do not edit.
export const knowledgePayload = {
  "meta": {
    "name": "NRadio 鲲鹏无限知识库",
    "generated_at": "2026-08-02T00:00:00.000Z",
    "verified_at": "2026-08-02",
    "entry_count": 23,
    "notice": "成员上传资料默认允许收录；动态内容按条目中的日期和适用条件理解。"
  },
  "entries": [
    {
      "id": "company-001",
      "title": "鲲鹏无限公司与品牌",
      "text": "鲲鹏无限的公司主体为深圳鲲鹏无限科技有限公司，品牌英文名为 NRadio。官方帮助中心称公司创立于 2016 年，是国家高新技术企业和深圳专精特新企业，定位为 5G 无线宽带产品专业厂商。",
      "source_url": "https://help.nradiowifi.com/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_help",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "公司",
        "品牌",
        "NRadio",
        "鲲鹏无限"
      ]
    },
    {
      "id": "company-002",
      "title": "鲲鹏无限团队与创始人介绍",
      "text": "官方帮助中心称，鲲鹏无限核心团队成员来自 TP-LINK、华为、中兴、极路由等通信品牌厂商；创始人张利鹏毕业于清华大学计算机系，并在通信行业深耕十年以上。",
      "source_url": "https://help.nradiowifi.com/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_help",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "创始人",
        "张利鹏",
        "团队",
        "公司介绍"
      ]
    },
    {
      "id": "company-003",
      "title": "鲲鹏无限主要业务",
      "text": "鲲鹏无限主要提供 4G 和 5G 无线宽带产品，覆盖便携旅行和固定上网两类形态，强调无需铺设传统有线宽带、部署灵活和随用随开。",
      "source_url": "https://help.nradiowifi.com/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_help",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "业务",
        "无线宽带",
        "5G CPE",
        "免拉线"
      ]
    },
    {
      "id": "product-001",
      "title": "鲲鹏无限官网产品分类",
      "text": "官网产品中心在 2026 年 7 月 30 日可见的产品类别包括 5G CPE、5G RedCap、全球漫游和高密度 WiFi。选型时应结合完整型号、使用地区、运营商、移动或固定场景、终端数量、网口及供电需求。",
      "source_url": "https://www.nradiowifi.com/chanpin/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "产品中心",
        "产品分类",
        "选型"
      ]
    },
    {
      "id": "product-002",
      "title": "C8 系列代表型号",
      "text": "官网在 2026 年 7 月 30 日可见的 C8 系列代表型号包括 C8-788、C8-618、C8-668GL 和 C8-688。相近名称可能对应不同芯片、地区版本、卡槽、频段或接口，回答参数时必须使用完整型号后缀。",
      "source_url": "https://www.nradiowifi.com/chanpin/fengwozuwang/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "5G CPE",
        "C8-788",
        "C8-618",
        "C8-668GL",
        "C8-688"
      ]
    },
    {
      "id": "product-003",
      "title": "C2000 与 C5800 系列代表型号",
      "text": "官网在 2026 年 7 月 30 日可见 C2000 MAX、C2000-518、C2000-500、C5800-668GL、C5800-688 和 C5800-650。C2000 系列包含 Mini 5G CPE，C5800 系列包含企业级四卡槽 5G CPE；不同后缀的芯片和配置不可混用。",
      "source_url": "https://www.nradiowifi.com/chanpin/fengwozuwang/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "5G CPE",
        "C2000 MAX",
        "C2000",
        "C5800",
        "企业网络"
      ]
    },
    {
      "id": "product-004",
      "title": "NBCPE、NBPCE 与户外版代表型号",
      "text": "官网在 2026 年 7 月 30 日可见 NBCPE-668GL、NBPCE-688、NBPCE-650 等 NB68 与 AK68 组合形态，以及 AK68-788 户外版。不同组合和后缀对应的地区、芯片或配置不同，不能视为同一型号。",
      "source_url": "https://www.nradiowifi.com/chanpin/fengwozuwang/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "NBCPE",
        "NBPCE",
        "NB68",
        "AK68",
        "户外CPE"
      ]
    },
    {
      "id": "product-005",
      "title": "RedCap、Nano CPE 与随身 WiFi 型号",
      "text": "官网在 2026 年 7 月 30 日可见 A8-510 RedCap 5G 移动路由器 CPE、DD-510 Nano 5G CPE、CC-500 与 CC-500 Pro 随身 WiFi，以及 TT-500、TK-500 随身快充 WiFi。",
      "source_url": "https://www.nradiowifi.com/chanpin/qiyezuwang/1/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "RedCap",
        "A8-510",
        "DD-510",
        "随身WiFi",
        "便携"
      ]
    },
    {
      "id": "product-006",
      "title": "全球漫游与高密度 WiFi 产品",
      "text": "官网在 2026 年 7 月 30 日可见 CC-100GL、TT-100GL、TK-100GL 等全球漫游便携产品，以及 E2000-R 高密度无线接入点和 N6700 AX6000 Wi-Fi 6 四频缓存路由器。全球漫游的实际国家、频段、运营商、套餐和资费应按具体型号及当前服务说明确认。",
      "source_url": "https://www.nradiowifi.com/chanpin/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "全球漫游",
        "高密度WiFi",
        "CC-100GL",
        "E2000-R",
        "N6700"
      ]
    },
    {
      "id": "account-001",
      "title": "张导严选小店抖音账号",
      "text": "用户提供的短链接解析为“张导严选小店”，抖音号为 70326957594，页面标注为店铺账号，IP 属地广东。该账号可作为选品与交易入口；价格、库存、优惠、发货和售后以当前商品页及订单页面显示为准。",
      "source_url": "https://v.douyin.com/IPb2vXHhDqs/",
      "uploaded_by": "FallaxAura",
      "source_type": "douyin_profile",
      "verified_at": "2026-07-30",
      "confidence": "medium_high",
      "tags": [
        "抖音",
        "张导严选小店",
        "店铺",
        "购买渠道"
      ]
    },
    {
      "id": "account-002",
      "title": "鲲鹏张导抖音账号",
      "text": "用户提供的短链接解析为“鲲鹏张导”，抖音号为 kpzd，IP 属地广东。核对时的公开简介为“鲲鹏CEO张导：清华本硕｜新疆放羊娃”，账号内容围绕 5G 免拉线网络、产品和使用场景展开。",
      "source_url": "https://v.douyin.com/SkNGZ72_cAs/",
      "uploaded_by": "FallaxAura",
      "source_type": "douyin_profile",
      "verified_at": "2026-07-30",
      "confidence": "medium_high",
      "tags": [
        "抖音",
        "鲲鹏张导",
        "张导",
        "kpzd"
      ]
    },
    {
      "id": "content-001",
      "title": "鲲鹏张导公开视频内容主题",
      "text": "公开可检索作品涉及 NBCPE、C2000 MAX、DD 等产品在车辆、房车、偏远作业区、展会直播、人群密集场所和租房场景中的应用，也包括信号寻找、设备对比、产品拆解、刷机和用户共创。具体视频中的测速、信号或场景效果对应当时的设备、位置和网络条件。",
      "source_url": "https://jingxuan.douyin.com/m/video/7632271688436043059",
      "uploaded_by": "FallaxAura",
      "source_type": "douyin_video",
      "verified_at": "2026-07-30",
      "confidence": "medium",
      "tags": [
        "使用场景",
        "NBCPE",
        "C2000 MAX",
        "DD",
        "公开视频"
      ]
    },
    {
      "id": "policy-001",
      "title": "C8-660 开放刷机信息",
      "text": "鲲鹏张导的公开视频曾介绍 C8-660 的开放刷机和社区共创策略，并邀请开源社区参与适配。这项信息针对 C8-660 及视频发布时的策略；其他型号是否支持刷机，应根据对应硬件版本和当前固件资料确认。",
      "source_url": "https://jingxuan.douyin.com/m/video/7298330506465119551",
      "uploaded_by": "FallaxAura",
      "source_type": "douyin_video",
      "verified_at": "2026-07-30",
      "confidence": "medium",
      "tags": [
        "C8-660",
        "开放刷机",
        "开源",
        "社区共创"
      ]
    },
    {
      "id": "faq-001",
      "title": "什么是 5G CPE",
      "text": "5G CPE 接收运营商的 5G 或 4G 蜂窝网络，再通过 WiFi 或网口为手机、电脑、摄像头等终端提供网络。它适合不方便安装有线宽带、需要临时网络、经常移动或希望快速部署网络的场景。",
      "source_url": "https://help.nradiowifi.com/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_help",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "FAQ",
        "5G CPE",
        "原理",
        "无线宽带"
      ]
    },
    {
      "id": "faq-002",
      "title": "5G CPE 选型前需要确认的信息",
      "text": "推荐 5G CPE 前，应确认使用国家、城市和具体区域，运营商与 SIM 卡套餐，固定或移动使用，室内或户外，同时接入设备数，以及是否需要 2.5G 网口、双卡或多卡、全球漫游、电池、快充、外置天线、户外安装或开放刷机，并了解预算范围。",
      "source_url": "https://www.nradiowifi.com/chanpin/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "FAQ",
        "选型",
        "需求收集",
        "导购"
      ]
    },
    {
      "id": "faq-003",
      "title": "鲲鹏产品可能适用的场景",
      "text": "官网与鲲鹏张导的公开视频涉及家庭或出租屋免拉线宽带、车辆和房车网络、展会或户外直播、偏远作业区、旅行随身网络和企业多终端接入。实际选型需要结合所在地信号、运营商、终端数、移动性、接口、天线和供电条件。",
      "source_url": "https://www.nradiowifi.com/chanpin/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "medium_high",
      "tags": [
        "FAQ",
        "使用场景",
        "家庭网络",
        "房车",
        "直播",
        "企业网络"
      ]
    },
    {
      "id": "faq-004",
      "title": "同一地点不同设备速度不同的原因",
      "text": "同一地点的不同设备可能因蜂窝频段和载波聚合能力、芯片与天线设计、SIM 卡套餐或限速策略、连接基站、设备摆放遮挡以及测试时网络拥塞程度不同而出现速度差异。公平比较应尽量使用同一 SIM 卡、同一位置、相近时间和同一测速服务器。",
      "source_url": "https://help.nradiowifi.com/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_help",
      "verified_at": "2026-07-30",
      "confidence": "medium_high",
      "tags": [
        "FAQ",
        "测速",
        "信号",
        "速度差异",
        "排障"
      ]
    },
    {
      "id": "faq-005",
      "title": "免拉线宽带与有线宽带的区别",
      "text": "免拉线宽带的主要优势是部署灵活，实际速度和稳定性会随信号、基站容量、蜂窝频段、套餐和环境变化。有线宽带通常更稳定；选择哪种方案应结合安装条件、移动需求、成本和当地网络质量。",
      "source_url": "https://help.nradiowifi.com/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_help",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "FAQ",
        "免拉线",
        "有线宽带",
        "稳定性"
      ]
    },
    {
      "id": "faq-006",
      "title": "全球旅行多达 165 个国家的含义",
      "text": "官方帮助中心使用过“海外旅行商务多达 165 个国家可以做到开机就上网”的宣传表述。具体可用国家、蜂窝频段、合作运营商、漫游套餐、资费和公平使用规则会随产品及服务变化，出行前应按目的地和完整型号查看最新说明。",
      "source_url": "https://help.nradiowifi.com/",
      "uploaded_by": "FallaxAura",
      "source_type": "official_help",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "FAQ",
        "全球漫游",
        "165个国家",
        "旅行网络"
      ]
    },
    {
      "id": "faq-007",
      "title": "价格、库存和活动信息怎么确认",
      "text": "产品价格、库存、优惠、发货时间和活动规则应以查询当时的官网商城、官方店铺、直播间或订单页面为准。历史视频中的粉丝价、首发价和限时活动只代表当时信息。",
      "source_url": "https://v.douyin.com/IPb2vXHhDqs/",
      "uploaded_by": "FallaxAura",
      "source_type": "douyin_profile",
      "verified_at": "2026-07-30",
      "confidence": "medium_high",
      "tags": [
        "FAQ",
        "价格",
        "库存",
        "活动",
        "发货"
      ]
    },
    {
      "id": "risk-001",
      "title": "产品参数、图片和测试数据的适用条件",
      "text": "官网说明产品图片、软件界面和实验室数据可能因产品版本、批次、生产供应、软件版本、使用条件和环境不同而变化，最终以实物和实际使用情况为准。回答具体参数时应使用完整型号和对应资料，不能用相近型号的数据代替。",
      "source_url": "https://www.nradiowifi.com/article/207.html",
      "uploaded_by": "FallaxAura",
      "source_type": "official_web",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "参数",
        "产品图片",
        "实验室数据",
        "型号",
        "适用条件"
      ]
    },
    {
      "id": "upload-20260730-27d9403f68-01",
      "title": "小助理企业微信被封临时联系方式",
      "text": "2026年7月29日，小助理企业微信被封，临时可通过QQ联系。恢复后恢复微信交流。QQ号：猫猫：1403713828，林林：242150291，好好：3293869279。",
      "source_url": "https://github.com/NRadio-Bot/nradio-platform/blob/main/knowledge-base/sources/uploads/2026-07/6d5727f8-5810-4397-9898-98c9f6991beb-未命名.txt",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-07-30",
      "confidence": "high",
      "tags": [
        "企业微信",
        "QQ",
        "联系方式",
        "临时",
        "2026-07-29"
      ]
    },
    {
      "id": "upload-20260802-ff3101ca0f-01",
      "title": "NRadio 知识库导入链路测试记录",
      "text": "NRadio 知识库导入链路测试，测试日期：2026-08-03。本条内容仅用于验证上传、模型整理、固定审核分支和 Draft PR 流程，不代表正式产品信息。",
      "source_url": "https://github.com/NRadio-test/nradio-web-platform/blob/main/knowledge-base/sources/uploads/2026-08/29f38c07-581c-4494-b13d-6b7dc95f2153-ceshi.txt",
      "source_type": "user_upload",
      "uploaded_by": "FallaxAura",
      "verified_at": "2026-08-02",
      "confidence": "high",
      "tags": [
        "NRadio",
        "知识库",
        "导入链路",
        "测试",
        "2026-08-03",
        "Draft PR"
      ]
    }
  ]
}
